const fs = require('fs');

let STONE_TYPES = {
    'andesite': 'andesite',
    'arkose': 'arkose',
    'basalt': 'basalt',
    'blaimorite': 'blaimorite',
    'blueschist': 'blueschist',
    'boninite': 'boninite',
    'carbonatite': 'carbonatite',
    'cataclasite': 'cataclasite',
    'chalk': 'chalk',
    'chert': 'chert',
    'claystone': 'claystone',
    'conglomerate': 'conglomerate',
    'dacite': 'dacite',
    'diorite': 'diorite',
    'dolomite': 'dolomite',
    'foidolite': 'foidolite',
    'gabbro': 'gabbro',
    'gneiss': 'gneiss',
    'granite': 'granite',
    'greenschist': 'greenschist',
    'jaspillite': 'jaspillite',
    'limestone': 'limestone',
    'marble': 'marble',
    'mylonite': 'mylonite',
    'phyllite': 'phyllite',
    'quartzite': 'quartzite',
    'rhyolite': 'rhyolite',
    'rocksalt': 'rocksalt',
    'schist': 'schist',
    'shale': 'shale',
    'slate': 'slate',
    'travertine': 'travertine',
    'wackestone': 'wackestone',
	'breccia': 'breccia',
    'porphyry': 'porphyry',
    'peridotite': 'peridotite',
    'mudstone': 'mudstone',
    'sandstone': 'sandstone',
    'siltstone': 'siltstone',
    'catlinite': 'catlinite',
    'novaculite': 'novaculite',
    'soapstone': 'soapstone',
    'komatiite': 'komatiite'
}


for(let stoneType of Object.keys(STONE_TYPES))
{
    generateRecipes(stoneType)
}

function generateRecipes(stoneType)
{
        let mossy_raw_layerJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfc:blocks/stonetypes/raw/${stoneType}`,
              "particle": `tfc:blocks/stonetypes/raw/${stoneType}`,
              "moss": "tfcflorae:blocks/stonetypes/moss_overlay"
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let mossy_rawJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfcflorae:blocks/stonetypes/mossy_raw/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let mudJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfcflorae:blocks/stonetypes/mud/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let mud_bricksJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfcflorae:blocks/stonetypes/mud_bricks/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let coarse_dirtJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
      "model": "cube_all",
      "textures": {
        "all": `tfcflorae:blocks/stonetypes/coarse_dirt/${stoneType}`
      }
      },
      "variants": {
      "normal": [
        {}
      ]
      }
    }
    let podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/dirt/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    // Blocks
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/mossy_raw_layer/${stoneType}.json`, JSON.stringify(mossy_raw_layerJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/mossy_raw/${stoneType}.json`, JSON.stringify(mossy_rawJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/mud/${stoneType}.json`, JSON.stringify(mudJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/mud_bricks/${stoneType}.json`, JSON.stringify(mud_bricksJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_dirt/${stoneType}.json`, JSON.stringify(coarse_dirtJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/podzol/${stoneType}.json`, JSON.stringify(podzolJSON, null, 2))


    let loamy_sandJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/loamy_sand/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_loamy_sandJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_loamy_sand/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let sandy_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/sandy_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_sandy_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_sandy_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let sandy_clay_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/sandy_clay_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_sandy_clay_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_sandy_clay_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let sandy_clayJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/sandy_clay/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_sandy_clayJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_sandy_clay/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let clay_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/clay_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_clay_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_clay_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let coarse_clayJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_clay/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let silty_clayJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/silty_clay/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_silty_clayJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_silty_clay/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let silt_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/silt_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_silt_loamJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_silt_loam/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    let siltJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/silt/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let coarse_siltJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/coarse_silt/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let humusJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/humus/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }
    let clay_humusJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "cube_all",
        "textures": {
          "all": `tfcflorae:blocks/stonetypes/clay_humus/${stoneType}`
        }
      },
      "variants": {
        "normal": [
          {}
        ]
      }
    }

    // Soils
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loamy_sand/${stoneType}.json`, JSON.stringify(loamy_sandJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_loamy_sand/${stoneType}.json`, JSON.stringify(coarse_loamy_sandJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_loam/${stoneType}.json`, JSON.stringify(sandy_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_sandy_loam/${stoneType}.json`, JSON.stringify(coarse_sandy_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_clay_loam/${stoneType}.json`, JSON.stringify(sandy_clay_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_sandy_clay_loam/${stoneType}.json`, JSON.stringify(coarse_sandy_clay_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_clay/${stoneType}.json`, JSON.stringify(sandy_clayJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_sandy_clay/${stoneType}.json`, JSON.stringify(coarse_sandy_clayJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loam/${stoneType}.json`, JSON.stringify(loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_loam/${stoneType}.json`, JSON.stringify(coarse_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/clay_loam/${stoneType}.json`, JSON.stringify(clay_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_clay_loam/${stoneType}.json`, JSON.stringify(coarse_clay_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_clay/${stoneType}.json`, JSON.stringify(coarse_clayJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silty_clay/${stoneType}.json`, JSON.stringify(silty_clayJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_silty_clay/${stoneType}.json`, JSON.stringify(coarse_silty_clayJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt_loam/${stoneType}.json`, JSON.stringify(silt_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_silt_loam/${stoneType}.json`, JSON.stringify(coarse_silt_loamJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt/${stoneType}.json`, JSON.stringify(siltJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/coarse_silt/${stoneType}.json`, JSON.stringify(coarse_siltJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/humus/${stoneType}.json`, JSON.stringify(humusJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/clay_humus/${stoneType}.json`, JSON.stringify(clay_humusJSON, null, 2))


    let dry_loamy_sand_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/loamy_sand/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let loamy_sand_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/loamy_sand/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let loamy_sand_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/loamy_sand/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_sandy_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let sandy_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let sandy_loam_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_loam/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_sandy_clay_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_clay_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let sandy_clay_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_clay_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let sandy_clay_loam_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_clay_loam/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_sandy_clay_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_clay/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let sandy_clay_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_clay/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let sandy_clay_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/sandy_clay/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let loam_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/loam/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_clay_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/clay_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let clay_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/clay_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let clay_loam_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/clay_loam/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_silty_clay_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silty_clay/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let silty_clay_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silty_clay/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let silty_clay_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silty_clay/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_silt_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silt_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let silt_loam_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silt_loam/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let silt_loam_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silt_loam/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    
    let dry_silt_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silt/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let silt_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silt/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let silt_podzolJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/silt/${stoneType}`,
          "particle": "tfcflorae:blocks/podzol_top",
          "top": "tfcflorae:blocks/podzol_top",
          "north": "tfcflorae:blocks/podzol_side",
          "south": "tfcflorae:blocks/podzol_side",
          "east": "tfcflorae:blocks/podzol_side",
          "west": "tfcflorae:blocks/podzol_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfcflorae:blocks/podzol_top"
            }
          },
          "false": {}
        }
      }
    }
    let surface_rockJSON = {
		"__comment":"Generated by generateResources.py function: blockstate",
		"forge_marker":1,
		"defaults":{
			"model":"item/generated",
			"textures":{
				"particle": `tfc:blocks/stonetypes/raw/${stoneType}`,
				"texture": `tfc:blocks/stonetypes/raw/${stoneType}`,
				"layer0": `tfcflorae:items/surface_rock/${stoneType}`
			}
		},
		"variants":{
			"normal":[
				{
					"model":"tfcflorae:surface_rock/rock_1",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_2",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_2_ne",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_2_none",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_2_nse",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_3",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_3_n",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_3_ne",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_3_none",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_4",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_5",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_5_ne",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_5_none",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_5_nse",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_6",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_6_n",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_6_ne",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_6_nse",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_7",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_7_n",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_7_ne",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_7_none",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_7_ns",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_7_nse",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_8",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_8_n",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_8_ne",
					"weight":20
				},
				{
					"model":"tfcflorae:surface_rock/rock_8_none",
					"weight":20
				}
			]
		}
	}
    let surface_rock_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "item/generated",
	  "textures": {
		"layer0": `tfcflorae:items/surface/rock/${stoneType}`
	  }
	}
    let dry_humus_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/humus/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/dry_grass_top",
          "north": "tfc:blocks/dry_grass_side",
          "south": "tfc:blocks/dry_grass_side",
          "east": "tfc:blocks/dry_grass_side",
          "west": "tfc:blocks/dry_grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/dry_grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let humus_grassJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "tfc:grass",
        "textures": {
          "all": `tfc:blocks/stonetypes/humus/${stoneType}`,
          "particle": "tfc:blocks/grass_top",
          "top": "tfc:blocks/grass_top",
          "north": "tfc:blocks/grass_side",
          "south": "tfc:blocks/grass_side",
          "east": "tfc:blocks/grass_side",
          "west": "tfc:blocks/grass_side"
        }
      },
      "variants": {
        "normal": [
          {}
        ],
        "north": {
          "true": {
            "textures": {
              "north": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "south": {
          "true": {
            "textures": {
              "south": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "east": {
          "true": {
            "textures": {
              "east": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        },
        "west": {
          "true": {
            "textures": {
              "west": "tfc:blocks/grass_top"
            }
          },
          "false": {}
        }
      }
    }
    let loamy_sand_farmlandJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:farmland",
		"textures": {
		  "dirt": `tfcflorae:blocks/stonetypes/loamy_sand/${stoneType}`,
		  "particle": `tfcflorae:blocks/stonetypes/loamy_sand/${stoneType}`,
		  "top": `tfcflorae:blocks/stonetypes/loamy_sand_farmland/${stoneType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let sandy_loam_farmlandJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:farmland",
		"textures": {
		  "dirt": `tfcflorae:blocks/stonetypes/sandy_loam/${stoneType}`,
		  "particle": `tfcflorae:blocks/stonetypes/sandy_loam/${stoneType}`,
		  "top": `tfcflorae:blocks/stonetypes/sandy_loam_farmland/${stoneType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let loam_farmlandJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:farmland",
		"textures": {
		  "dirt": `tfcflorae:blocks/stonetypes/loam/${stoneType}`,
		  "particle": `tfcflorae:blocks/stonetypes/loam/${stoneType}`,
		  "top": `tfcflorae:blocks/stonetypes/loam_farmland/${stoneType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let silt_loam_farmlandJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:farmland",
		"textures": {
		  "dirt": `tfcflorae:blocks/stonetypes/silt_loam/${stoneType}`,
		  "particle": `tfcflorae:blocks/stonetypes/silt_loam/${stoneType}`,
		  "top": `tfcflorae:blocks/stonetypes/silt_loam_farmland/${stoneType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let silt_farmlandJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:farmland",
		"textures": {
		  "dirt": `tfcflorae:blocks/stonetypes/silt/${stoneType}`,
		  "particle": `tfcflorae:blocks/stonetypes/silt/${stoneType}`,
		  "top": `tfcflorae:blocks/stonetypes/silt_farmland/${stoneType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let humus_farmlandJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:farmland",
		"textures": {
		  "dirt": `tfcflorae:blocks/stonetypes/humus/${stoneType}`,
		  "particle": `tfcflorae:blocks/stonetypes/humus/${stoneType}`,
		  "top": `tfcflorae:blocks/stonetypes/humus_farmland/${stoneType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}

    // Grasses
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_loamy_sand_grass/${stoneType}.json`, JSON.stringify(dry_loamy_sand_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loamy_sand_grass/${stoneType}.json`, JSON.stringify(loamy_sand_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loamy_sand_podzol/${stoneType}.json`, JSON.stringify(loamy_sand_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_sandy_loam_grass/${stoneType}.json`, JSON.stringify(dry_sandy_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_loam_grass/${stoneType}.json`, JSON.stringify(sandy_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_loam_podzol/${stoneType}.json`, JSON.stringify(sandy_loam_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_sandy_clay_loam_grass/${stoneType}.json`, JSON.stringify(dry_sandy_clay_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_clay_loam_grass/${stoneType}.json`, JSON.stringify(sandy_clay_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_clay_loam_podzol/${stoneType}.json`, JSON.stringify(sandy_clay_loam_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_sandy_clay_grass/${stoneType}.json`, JSON.stringify(dry_sandy_clay_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_clay_grass/${stoneType}.json`, JSON.stringify(sandy_clay_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_clay_podzol/${stoneType}.json`, JSON.stringify(sandy_clay_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_loam_grass/${stoneType}.json`, JSON.stringify(dry_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loam_grass/${stoneType}.json`, JSON.stringify(loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loam_podzol/${stoneType}.json`, JSON.stringify(loam_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_clay_loam_grass/${stoneType}.json`, JSON.stringify(dry_clay_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/clay_loam_grass/${stoneType}.json`, JSON.stringify(clay_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/clay_loam_podzol/${stoneType}.json`, JSON.stringify(clay_loam_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_silty_clay_grass/${stoneType}.json`, JSON.stringify(dry_silty_clay_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silty_clay_grass/${stoneType}.json`, JSON.stringify(silty_clay_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silty_clay_podzol/${stoneType}.json`, JSON.stringify(silty_clay_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_silt_loam_grass/${stoneType}.json`, JSON.stringify(dry_silt_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt_loam_grass/${stoneType}.json`, JSON.stringify(silt_loam_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt_loam_podzol/${stoneType}.json`, JSON.stringify(silt_loam_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_silt_grass/${stoneType}.json`, JSON.stringify(dry_silt_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt_grass/${stoneType}.json`, JSON.stringify(silt_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt_podzol/${stoneType}.json`, JSON.stringify(silt_podzolJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/surface_rock/${stoneType}.json`, JSON.stringify(surface_rockJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/surface/rock/${stoneType}.json`, JSON.stringify(surface_rock_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/dry_humus_grass/${stoneType}.json`, JSON.stringify(dry_humus_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/humus_grass/${stoneType}.json`, JSON.stringify(humus_grassJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loamy_sand_farmland/${stoneType}.json`, JSON.stringify(loamy_sand_farmlandJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/sandy_loam_farmland/${stoneType}.json`, JSON.stringify(sandy_loam_farmlandJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/loam_farmland/${stoneType}.json`, JSON.stringify(loam_farmlandJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt_loam_farmland/${stoneType}.json`, JSON.stringify(silt_loam_farmlandJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/silt_farmland/${stoneType}.json`, JSON.stringify(silt_farmlandJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/humus_farmland/${stoneType}.json`, JSON.stringify(humus_farmlandJSON, null, 2))

    
    let mud_itemJSON = {
      "__comment": "Generated by generateResources.py function: model",
      "parent": "item/generated",
      "textures": {
        "layer0": `tfcflorae:items/mud/${stoneType}`
      }
    }
    let mud_brick_itemJSON = {
      "__comment": "Generated by generateResources.py function: model",
      "parent": "item/generated",
      "textures": {
        "layer0": `tfcflorae:items/mud_brick/${stoneType}`
      }
    }

    // Items
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/mud/${stoneType}.json`, JSON.stringify(mud_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/mud_brick/${stoneType}.json`, JSON.stringify(mud_brick_itemJSON, null, 2))


    let coarse_dirt_recipeJSON = {
      "type": "minecraft:crafting_shaped",
      "pattern": [
      "BX",
      "XB"
      ],
      "key": {
      "X": {
        "type": "forge:ore_dict",
        "ore": `tfc:gravel/${stoneType}`
        },
          "B": {
        "type": "forge:ore_dict",
        "ore": `tfc:dirt/${stoneType}`
          }
      },
      "result": {
      "item": `tfcflorae:coarse_dirt/${stoneType}`,
      "count": 4
      }
    }
    let mud_bricks_recipeJSON = {
	  "__comment": "Generated by generateResources.py function: shaped_recipe",
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XOX",
		"OXO",
		"XOX"
	  ],
	  "key": {
		"O": {
		  "type": "forge:ore_dict",
		  "ore": "mortar"
		},
		"X": {
		  "item": `tfcflorae:mud/fired/mud_brick/${stoneType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:mud_bricks/${stoneType}`,
		"count": 6
	  }
	}
    let mud_bricks_slab_recipeJSON = {
	  "__comment": "Generated by generateResources.py function: shaped_recipe",
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:mud_bricks/${stoneType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:slab/mud_bricks/${stoneType}`,
		"count": 8
	  }
	}
    let mud_bricks_stairs_recipeJSON = {
	  "__comment": "Generated by generateResources.py function: shaped_recipe",
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"X  ",
		"XX ",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:mud_bricks/${stoneType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:stairs/mud_bricks/${stoneType}`,
		"count": 8
	  }
	}
    let mud_bricks_wall_recipeJSON = {
	  "__comment": "Generated by generateResources.py function: shaped_recipe",
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:mud_bricks/${stoneType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wall/mud_bricks/${stoneType}`,
		"count": 8
	  }
	}
	
	
    let coarse_loamy_sand_recipeJSON = {
      "type": "minecraft:crafting_shaped",
      "pattern": [
      "BX",
      "XB"
      ],
      "key": {
      "X": {
        "type": "forge:ore_dict",
        "ore": `tfc:gravel/${stoneType}`
        },
          "B": {
        "type": "forge:ore_dict",
        "ore": `tfcflorae:loamy_sand/${stoneType}`
          }
      },
      "result": {
      "item": `tfcflorae:coarse_loamy_sand/${stoneType}`,
      "count": 4
      }
    }
    let coarse_sandy_loam_recipeJSON = {
      "type": "minecraft:crafting_shaped",
      "pattern": [
      "BX",
      "XB"
      ],
      "key": {
      "X": {
        "type": "forge:ore_dict",
        "ore": `tfc:gravel/${stoneType}`
        },
          "B": {
        "type": "forge:ore_dict",
        "ore": `tfcflorae:sandy_loam/${stoneType}`
          }
      },
      "result": {
      "item": `tfcflorae:coarse_sandy_loam/${stoneType}`,
      "count": 4
      }
    }
    let coarse_loam_recipeJSON = {
      "type": "minecraft:crafting_shaped",
      "pattern": [
      "BX",
      "XB"
      ],
      "key": {
      "X": {
        "type": "forge:ore_dict",
        "ore": `tfc:gravel/${stoneType}`
        },
          "B": {
        "type": "forge:ore_dict",
        "ore": `tfcflorae:loam/${stoneType}`
          }
      },
      "result": {
      "item": `tfcflorae:coarse_loam/${stoneType}`,
      "count": 4
      }
    }
    let coarse_silt_loam_recipeJSON = {
      "type": "minecraft:crafting_shaped",
      "pattern": [
      "BX",
      "XB"
      ],
      "key": {
      "X": {
        "type": "forge:ore_dict",
        "ore": `tfc:gravel/${stoneType}`
        },
          "B": {
        "type": "forge:ore_dict",
        "ore": `tfcflorae:silt_loam/${stoneType}`
          }
      },
      "result": {
      "item": `tfcflorae:coarse_silt_loam/${stoneType}`,
      "count": 4
      }
    }
    let coarse_silt_recipeJSON = {
      "type": "minecraft:crafting_shaped",
      "pattern": [
      "BX",
      "XB"
      ],
      "key": {
      "X": {
        "type": "forge:ore_dict",
        "ore": `tfc:gravel/${stoneType}`
        },
          "B": {
        "type": "forge:ore_dict",
        "ore": `tfcflorae:silt/${stoneType}`
          }
      },
      "result": {
      "item": `tfcflorae:coarse_silt/${stoneType}`,
      "count": 4
      }
    }
    let coarse_humus_recipeJSON = {
      "type": "minecraft:crafting_shaped",
      "pattern": [
      "BX",
      "XB"
      ],
      "key": {
      "X": {
        "type": "forge:ore_dict",
        "ore": `tfc:gravel/${stoneType}`
        },
          "B": {
        "type": "forge:ore_dict",
        "ore": `tfcflorae:humus/${stoneType}`
          }
      },
      "result": {
      "item": `tfcflorae:coarse_humus/${stoneType}`,
      "count": 4
      }
    }

    // Recipes
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/coarse_dirt/${stoneType}.json`, JSON.stringify(coarse_dirt_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/mud_bricks/${stoneType}.json`, JSON.stringify(mud_bricks_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/slab/mud_bricks/${stoneType}.json`, JSON.stringify(mud_bricks_slab_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/stairs/mud_bricks/${stoneType}.json`, JSON.stringify(mud_bricks_stairs_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/wall/mud_bricks/${stoneType}.json`, JSON.stringify(mud_bricks_wall_recipeJSON, null, 2))
	
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/coarse_loamy_sand/${stoneType}.json`, JSON.stringify(coarse_loamy_sand_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/coarse_sandy_loam/${stoneType}.json`, JSON.stringify(coarse_sandy_loam_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/coarse_loam/${stoneType}.json`, JSON.stringify(coarse_loam_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/coarse_silt_loam/${stoneType}.json`, JSON.stringify(coarse_silt_loam_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/coarse_silt/${stoneType}.json`, JSON.stringify(coarse_silt_recipeJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/stone/coarse_humus/${stoneType}.json`, JSON.stringify(coarse_humus_recipeJSON, null, 2))
}
