const fs = require('fs');

let FRUIT_WOOD_TYPES = {

    'arrow_bamboo': 'arrow_bamboo',
    'black_bamboo': 'black_bamboo',
    'blue_bamboo': 'blue_bamboo',
    'dragon_bamboo': 'dragon_bamboo',
    'golden_bamboo': 'golden_bamboo',
    'narrow_leaf_bamboo': 'narrow_leaf_bamboo',
    'red_bamboo': 'red_bamboo',
    'temple_bamboo': 'temple_bamboo',
    'thorny_bamboo': 'thorny_bamboo',
    'timber_bamboo': 'timber_bamboo',
    'tinwa_bamboo': 'tinwa_bamboo',
    'weavers_bamboo': 'weavers_bamboo'
}


for(let woodType of Object.keys(FRUIT_WOOD_TYPES))
{
    generateResources(woodType)
}

function generateResources(woodType)
{
    let barrelJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:barrel",
		"textures": {
		  "particle": `tfc:blocks/wood/planks/${woodType}`,
		  "planks": `tfc:blocks/wood/planks/${woodType}`,
		  "sheet": `tfc:blocks/wood/sheets/${woodType}`,
		  "hoop": "tfc:blocks/barrelhoop"
		}
	  },
	  "variants": {
		"normal": [
		  {}
		],
		"sealed": {
		  "true": {
			"model": "tfc:barrel_sealed"
		  },
		  "false": {}
		},
		"inventory": [
		  {}
		]
	  }
	}
    let bookshelfJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:bookshelf",
		"textures": {
		  "all": `tfc:blocks/wood/planks/${woodType}`,
		  "particle": `tfc:blocks/wood/planks/${woodType}`,
		  "north": "tfc:blocks/wood/bookshelf",
		  "south": "tfc:blocks/wood/bookshelf",
		  "east": "tfc:blocks/wood/bookshelf",
		  "west": "tfc:blocks/wood/bookshelf"
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let buttonJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "button",
		"textures": {
		  "texture": `tfc:blocks/wood/planks/${woodType}`,
		  "particle": `tfc:blocks/wood/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "button_inventory"
		  }
		],
		"powered": {
		  "false": {},
		  "true": {
			"model": "button_pressed"
		  }
		},
		"facing": {
		  "up": {},
		  "down": {
			"x": 180
		  },
		  "east": {
			"x": 90,
			"y": 90
		  },
		  "west": {
			"x": 90,
			"y": 270
		  },
		  "south": {
			"x": 90,
			"y": 180
		  },
		  "north": {
			"x": 90
		  }
		},
		"inventory": [
		  {
			"model": "button_inventory"
		  }
		]
	  }
	}
    let doorJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"textures": {
		  "bottom": `tfc:blocks/wood/door/lower/${woodType}`,
		  "top": `tfc:blocks/wood/door/upper/${woodType}`
		}
	  },
	  "variants": {
		"facing=east,half=lower,hinge=left,open=false": {
		  "model": "door_bottom"
		},
		"facing=south,half=lower,hinge=left,open=false": {
		  "model": "door_bottom",
		  "y": 90
		},
		"facing=west,half=lower,hinge=left,open=false": {
		  "model": "door_bottom",
		  "y": 180
		},
		"facing=north,half=lower,hinge=left,open=false": {
		  "model": "door_bottom",
		  "y": 270
		},
		"facing=east,half=lower,hinge=right,open=false": {
		  "model": "door_bottom_rh"
		},
		"facing=south,half=lower,hinge=right,open=false": {
		  "model": "door_bottom_rh",
		  "y": 90
		},
		"facing=west,half=lower,hinge=right,open=false": {
		  "model": "door_bottom_rh",
		  "y": 180
		},
		"facing=north,half=lower,hinge=right,open=false": {
		  "model": "door_bottom_rh",
		  "y": 270
		},
		"facing=east,half=lower,hinge=left,open=true": {
		  "model": "door_bottom_rh",
		  "y": 90
		},
		"facing=south,half=lower,hinge=left,open=true": {
		  "model": "door_bottom_rh",
		  "y": 180
		},
		"facing=west,half=lower,hinge=left,open=true": {
		  "model": "door_bottom_rh",
		  "y": 270
		},
		"facing=north,half=lower,hinge=left,open=true": {
		  "model": "door_bottom_rh"
		},
		"facing=east,half=lower,hinge=right,open=true": {
		  "model": "door_bottom",
		  "y": 270
		},
		"facing=south,half=lower,hinge=right,open=true": {
		  "model": "door_bottom"
		},
		"facing=west,half=lower,hinge=right,open=true": {
		  "model": "door_bottom",
		  "y": 90
		},
		"facing=north,half=lower,hinge=right,open=true": {
		  "model": "door_bottom",
		  "y": 180
		},
		"facing=east,half=upper,hinge=left,open=false": {
		  "model": "tfc:door_top_tfc"
		},
		"facing=south,half=upper,hinge=left,open=false": {
		  "model": "tfc:door_top_tfc",
		  "y": 90
		},
		"facing=west,half=upper,hinge=left,open=false": {
		  "model": "tfc:door_top_tfc",
		  "y": 180
		},
		"facing=north,half=upper,hinge=left,open=false": {
		  "model": "tfc:door_top_tfc",
		  "y": 270
		},
		"facing=east,half=upper,hinge=right,open=false": {
		  "model": "tfc:door_top_rh_tfc"
		},
		"facing=south,half=upper,hinge=right,open=false": {
		  "model": "tfc:door_top_rh_tfc",
		  "y": 90
		},
		"facing=west,half=upper,hinge=right,open=false": {
		  "model": "tfc:door_top_rh_tfc",
		  "y": 180
		},
		"facing=north,half=upper,hinge=right,open=false": {
		  "model": "tfc:door_top_rh_tfc",
		  "y": 270
		},
		"facing=east,half=upper,hinge=left,open=true": {
		  "model": "tfc:door_top_rh_tfc",
		  "y": 90
		},
		"facing=south,half=upper,hinge=left,open=true": {
		  "model": "tfc:door_top_rh_tfc",
		  "y": 180
		},
		"facing=west,half=upper,hinge=left,open=true": {
		  "model": "tfc:door_top_rh_tfc",
		  "y": 270
		},
		"facing=north,half=upper,hinge=left,open=true": {
		  "model": "tfc:door_top_rh_tfc"
		},
		"facing=east,half=upper,hinge=right,open=true": {
		  "model": "tfc:door_top_tfc",
		  "y": 270
		},
		"facing=south,half=upper,hinge=right,open=true": {
		  "model": "tfc:door_top_tfc"
		},
		"facing=west,half=upper,hinge=right,open=true": {
		  "model": "tfc:door_top_tfc",
		  "y": 90
		},
		"facing=north,half=upper,hinge=right,open=true": {
		  "model": "tfc:door_top_tfc",
		  "y": 180
		}
	  }
	}
    let double_slabJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "cube_all",
		"textures": {
		  "all": `tfc:blocks/wood/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let fenceJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "fence_post",
		"textures": {
		  "texture": `tfc:blocks/wood/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "fence_inventory"
		  }
		],
		"inventory": {
		  "model": "fence_inventory"
		},
		"north": {
		  "true": {
			"submodel": "fence_side"
		  },
		  "false": {}
		},
		"east": {
		  "true": {
			"submodel": "fence_side",
			"y": 90
		  },
		  "false": {}
		},
		"south": {
		  "true": {
			"submodel": "fence_side",
			"y": 180
		  },
		  "false": {}
		},
		"west": {
		  "true": {
			"submodel": "fence_side",
			"y": 270
		  },
		  "false": {}
		}
	  }
	}
    let fence_gateJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "fence_gate_closed",
		"textures": {
		  "texture": `tfc:blocks/wood/planks/${woodType}`
		},
		"uvlock": true
	  },
	  "variants": {
		"normal": [
		  {
			"model": "fence_gate_closed"
		  }
		],
		"facing=south,in_wall=false,open=false": {
		  "model": "fence_gate_closed"
		},
		"facing=west,in_wall=false,open=false": {
		  "model": "fence_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=false,open=false": {
		  "model": "fence_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=false,open=false": {
		  "model": "fence_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=false,open=true": {
		  "model": "fence_gate_open"
		},
		"facing=west,in_wall=false,open=true": {
		  "model": "fence_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=false,open=true": {
		  "model": "fence_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=false,open=true": {
		  "model": "fence_gate_open",
		  "y": 270
		},
		"facing=south,in_wall=true,open=false": {
		  "model": "wall_gate_closed"
		},
		"facing=west,in_wall=true,open=false": {
		  "model": "wall_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=true,open=false": {
		  "model": "wall_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=true,open=false": {
		  "model": "wall_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=true,open=true": {
		  "model": "wall_gate_open"
		},
		"facing=west,in_wall=true,open=true": {
		  "model": "wall_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=true,open=true": {
		  "model": "wall_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=true,open=true": {
		  "model": "wall_gate_open",
		  "y": 270
		}
	  }
	}
    let fence_gate_logJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		"textures": {
		  "log": `tfc:blocks/wood/log/${woodType}`,
		  "planks": `tfc:blocks/wood/planks/${woodType}`,
		  "particle": `tfc:blocks/wood/log/${woodType}`
		},
		"uvlock": true
	  },
	  "variants": {
		"normal": [
		  {
			"model": "tfcflorae:wood/fence_gate/fence_gate_closed"
		  }
		],
		"facing=south,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed"
		},
		"facing=west,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open"
		},
		"facing=west,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open",
		  "y": 270
		},
		"facing=south,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed"
		},
		"facing=west,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open"
		},
		"facing=west,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open",
		  "y": 270
		}
	  }
	}
    let fence_logJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfcflorae:wood/fence/fence_post",
		"textures": {
		  "top": `tfc:blocks/wood/fruit_tree/top/${woodType}`,
		  "log": `tfc:blocks/wood/fruit_tree/log/${woodType}`,
		  "planks": `tfc:blocks/wood/fruit_tree/planks/${woodType}`,
		  "particle": `tfc:blocks/wood/fruit_tree/log/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "tfcflorae:wood/fence/fence_inventory"
		  }
		],
		"inventory": {
		  "model": "tfcflorae:wood/fence/fence_inventory"
		},
		"north": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side"
		  },
		  "false": {}
		},
		"east": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side",
			"y": 90
		  },
		  "false": {}
		},
		"south": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side",
			"y": 180
		  },
		  "false": {}
		},
		"west": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side",
			"y": 270
		  },
		  "false": {}
		}
	  }
	}
    let leavesJSON = {
	  "forge_marker": 1,
	  "defaults": {
		"model": "leaves",
		"textures": {
		  "all": `tfc:blocks/wood/leaves/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let logJSON = {
		"forge_marker": 1,
		"defaults": {
			"model": "tfcflorae:wood/fruit_tree/log/log_thin",
			"textures": {
				"side": `tfc:blocks/wood/log/${woodType}`,
				"top": `tfc:blocks/wood/top/${woodType}`,
				"particle": `tfc:blocks/wood/log/${woodType}`
			}
		},
		"variants": {
			"grown": {
				"true": {
					"textures": {
						"particle": `tfc:blocks/wood/log/${woodType}`,
						"side": `tfc:blocks/wood/log/${woodType}`
					}
				},
				"false": {
					"textures": {
						"particle": `tfc:blocks/wood/sheets/${woodType}`,
						"side": `tfc:blocks/wood/sheets/${woodType}`
					},
					"model": "tfcflorae:wood/fruit_tree/log/log_stripped"
				}
			},
			"connected": {
				"true": {
					"model": "tfcflorae:wood/fruit_tree/log/log_connected"
				},
				"false": {}
			},
			"inventory": [{}],
			"normal": [{
				"transform": "forge:default-block",
				"model": "tfcflorae:wood/fruit_tree/log/log_thin"
			}]
		}
	}
    let planksJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "cube_all",
		"textures": {
		  "all": `tfc:blocks/wood/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let pressure_plateJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "pressure_plate",
		"textures": {
		  "texture": `tfc:blocks/wood/planks/${woodType}`,
		  "particle": `tfc:blocks/wood/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "stone_pressure_plate_up"
		  }
		],
		"powered": {
		  "false": {
			"model": "stone_pressure_plate_up"
		  },
		  "true": {
			"model": "stone_pressure_plate_down"
		  }
		},
		"inventory": [
		  {
			"model": "stone_pressure_plate_up"
		  }
		]
	  }
	}
    let saplingJSON = {
	  "forge_marker": 1,
	  "defaults": {
		"model": "cross",
		"textures": {
		  "cross": `tfc:blocks/wood/sapling/${woodType}`,
		  "layer0": `tfc:blocks/wood/sapling/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "builtin/generated",
			"transform": "forge:default-item"
		  }
		],
		"inventory": {
		  "model": "builtin/generated",
		  "transform": "forge:default-item"
		}
	  }
	}
    let slabJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "half_slab",
		"textures": {
		  "top": `tfc:blocks/wood/planks/${woodType}`,
		  "bottom": `tfc:blocks/wood/planks/${woodType}`,
		  "side": `tfc:blocks/wood/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		],
		"half": {
		  "bottom": {},
		  "top": {
			"model": "upper_slab"
		  }
		}
	  }
	}
    let stairsJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"textures": {
		  "top": `tfc:blocks/wood/planks/${woodType}`,
		  "bottom": `tfc:blocks/wood/planks/${woodType}`,
		  "side": `tfc:blocks/wood/planks/${woodType}`
		},
		"uvlock": true
	  },
	  "variants": {
		"normal": {
		  "model": "stairs"
		},
		"facing=east,half=bottom,shape=straight": {
		  "model": "stairs"
		},
		"facing=west,half=bottom,shape=straight": {
		  "model": "stairs",
		  "y": 180
		},
		"facing=south,half=bottom,shape=straight": {
		  "model": "stairs",
		  "y": 90
		},
		"facing=north,half=bottom,shape=straight": {
		  "model": "stairs",
		  "y": 270
		},
		"facing=east,half=bottom,shape=outer_right": {
		  "model": "outer_stairs"
		},
		"facing=west,half=bottom,shape=outer_right": {
		  "model": "outer_stairs",
		  "y": 180
		},
		"facing=south,half=bottom,shape=outer_right": {
		  "model": "outer_stairs",
		  "y": 90
		},
		"facing=north,half=bottom,shape=outer_right": {
		  "model": "outer_stairs",
		  "y": 270
		},
		"facing=east,half=bottom,shape=outer_left": {
		  "model": "outer_stairs",
		  "y": 270
		},
		"facing=west,half=bottom,shape=outer_left": {
		  "model": "outer_stairs",
		  "y": 90
		},
		"facing=south,half=bottom,shape=outer_left": {
		  "model": "outer_stairs"
		},
		"facing=north,half=bottom,shape=outer_left": {
		  "model": "outer_stairs",
		  "y": 180
		},
		"facing=east,half=bottom,shape=inner_right": {
		  "model": "inner_stairs"
		},
		"facing=west,half=bottom,shape=inner_right": {
		  "model": "inner_stairs",
		  "y": 180
		},
		"facing=south,half=bottom,shape=inner_right": {
		  "model": "inner_stairs",
		  "y": 90
		},
		"facing=north,half=bottom,shape=inner_right": {
		  "model": "inner_stairs",
		  "y": 270
		},
		"facing=east,half=bottom,shape=inner_left": {
		  "model": "inner_stairs",
		  "y": 270
		},
		"facing=west,half=bottom,shape=inner_left": {
		  "model": "inner_stairs",
		  "y": 90
		},
		"facing=south,half=bottom,shape=inner_left": {
		  "model": "inner_stairs"
		},
		"facing=north,half=bottom,shape=inner_left": {
		  "model": "inner_stairs",
		  "y": 180
		},
		"facing=east,half=top,shape=straight": {
		  "model": "stairs",
		  "x": 180
		},
		"facing=west,half=top,shape=straight": {
		  "model": "stairs",
		  "x": 180,
		  "y": 180
		},
		"facing=south,half=top,shape=straight": {
		  "model": "stairs",
		  "x": 180,
		  "y": 90
		},
		"facing=north,half=top,shape=straight": {
		  "model": "stairs",
		  "x": 180,
		  "y": 270
		},
		"facing=east,half=top,shape=outer_right": {
		  "model": "outer_stairs",
		  "x": 180,
		  "y": 90
		},
		"facing=west,half=top,shape=outer_right": {
		  "model": "outer_stairs",
		  "x": 180,
		  "y": 270
		},
		"facing=south,half=top,shape=outer_right": {
		  "model": "outer_stairs",
		  "x": 180,
		  "y": 180
		},
		"facing=north,half=top,shape=outer_right": {
		  "model": "outer_stairs",
		  "x": 180
		},
		"facing=east,half=top,shape=outer_left": {
		  "model": "outer_stairs",
		  "x": 180
		},
		"facing=west,half=top,shape=outer_left": {
		  "model": "outer_stairs",
		  "x": 180,
		  "y": 180
		},
		"facing=south,half=top,shape=outer_left": {
		  "model": "outer_stairs",
		  "x": 180,
		  "y": 90
		},
		"facing=north,half=top,shape=outer_left": {
		  "model": "outer_stairs",
		  "x": 180,
		  "y": 270
		},
		"facing=east,half=top,shape=inner_right": {
		  "model": "inner_stairs",
		  "x": 180,
		  "y": 90
		},
		"facing=west,half=top,shape=inner_right": {
		  "model": "inner_stairs",
		  "x": 180,
		  "y": 270
		},
		"facing=south,half=top,shape=inner_right": {
		  "model": "inner_stairs",
		  "x": 180,
		  "y": 180
		},
		"facing=north,half=top,shape=inner_right": {
		  "model": "inner_stairs",
		  "x": 180
		},
		"facing=east,half=top,shape=inner_left": {
		  "model": "inner_stairs",
		  "x": 180
		},
		"facing=west,half=top,shape=inner_left": {
		  "model": "inner_stairs",
		  "x": 180,
		  "y": 180
		},
		"facing=south,half=top,shape=inner_left": {
		  "model": "inner_stairs",
		  "x": 180,
		  "y": 90
		},
		"facing=north,half=top,shape=inner_left": {
		  "model": "inner_stairs",
		  "x": 180,
		  "y": 270
		}
	  }
	}
    let supportJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:support/vertical",
		"textures": {
		  "texture": `tfc:blocks/wood/sheets/${woodType}`,
		  "particle": `tfc:blocks/wood/sheets/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		],
		"inventory": {
		  "model": "tfc:support/inventory"
		},
		"axis": {
		  "y": {
			"model": "tfc:support/vertical"
		  },
		  "x": {
			"model": "tfc:support/horizontal"
		  },
		  "z": {
			"model": "tfc:support/horizontal",
			"y": 90
		  }
		},
		"north": {
		  "true": {
			"submodel": "tfc:support/connection",
			"y": 270
		  },
		  "false": {}
		},
		"east": {
		  "true": {
			"submodel": "tfc:support/connection"
		  },
		  "false": {}
		},
		"south": {
		  "true": {
			"submodel": "tfc:support/connection",
			"y": 90
		  },
		  "false": {}
		},
		"west": {
		  "true": {
			"submodel": "tfc:support/connection",
			"y": 180
		  },
		  "false": {}
		}
	  }
	}
    let tool_rackJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:tool_rack",
		"textures": {
		  "texture": `tfc:blocks/wood/planks/${woodType}`,
		  "particle": `tfc:blocks/wood/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		],
		"facing": {
		  "south": {},
		  "west": {
			"y": 90
		  },
		  "north": {
			"y": 180
		  },
		  "east": {
			"y": 270
		  }
		}
	  }
	}
    let trapdoorJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"textures": {
		  "texture": `tfc:blocks/wood/trapdoor/${woodType}`
		}
	  },
	  "variants": {
		"facing=north,half=bottom,open=false": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 180
		},
		"facing=south,half=bottom,open=false": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 180
		},
		"facing=east,half=bottom,open=false": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 180
		},
		"facing=west,half=bottom,open=false": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 180
		},
		"facing=north,half=top,open=false": {
		  "model": "tfc:trapdoor_tfc"
		},
		"facing=south,half=top,open=false": {
		  "model": "tfc:trapdoor_tfc"
		},
		"facing=east,half=top,open=false": {
		  "model": "tfc:trapdoor_tfc"
		},
		"facing=west,half=top,open=false": {
		  "model": "tfc:trapdoor_tfc"
		},
		"facing=north,half=bottom,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 270
		},
		"facing=south,half=bottom,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 90
		},
		"facing=east,half=bottom,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 270,
		  "y": 90
		},
		"facing=west,half=bottom,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 270,
		  "y": 270
		},
		"facing=north,half=top,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 270
		},
		"facing=south,half=top,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 90
		},
		"facing=east,half=top,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 270,
		  "y": 90
		},
		"facing=west,half=top,open=true": {
		  "model": "tfc:trapdoor_tfc",
		  "x": 270,
		  "y": 270
		}
	  }
	}
    let workbenchJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:workbench",
		"textures": {
		  "all": `tfc:blocks/wood/planks/${woodType}`,
		  "particle": `tfc:blocks/wood/planks/${woodType}`,
		  "top": "tfc:blocks/wood/workbench_top",
		  "north": "tfc:blocks/wood/workbench_front",
		  "south": "tfc:blocks/wood/workbench_front",
		  "east": "tfc:blocks/wood/workbench_side",
		  "west": "tfc:blocks/wood/workbench_side"
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}

    // Blockstates 
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/barrel/${woodType}.json`, JSON.stringify(barrelJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/bookshelf/${woodType}.json`, JSON.stringify(bookshelfJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/button/${woodType}.json`, JSON.stringify(buttonJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/door/${woodType}.json`, JSON.stringify(doorJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/double_slab/${woodType}.json`, JSON.stringify(double_slabJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/fence/${woodType}.json`, JSON.stringify(fenceJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/fence_gate/${woodType}.json`, JSON.stringify(fence_gateJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/fence_gate_log/${woodType}.json`, JSON.stringify(fence_gate_logJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/fence_log/${woodType}.json`, JSON.stringify(fence_logJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/leaves/${woodType}.json`, JSON.stringify(leavesJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/log/${woodType}.json`, JSON.stringify(logJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/planks/${woodType}.json`, JSON.stringify(planksJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/pressure_plate/${woodType}.json`, JSON.stringify(pressure_plateJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/sapling/${woodType}.json`, JSON.stringify(saplingJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/slab/${woodType}.json`, JSON.stringify(slabJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/stairs/${woodType}.json`, JSON.stringify(stairsJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/support/${woodType}.json`, JSON.stringify(supportJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/tool_rack/${woodType}.json`, JSON.stringify(tool_rackJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/trapdoor/${woodType}.json`, JSON.stringify(trapdoorJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/bamboo/workbench/${woodType}.json`, JSON.stringify(workbenchJSON, null, 2))


	
    let boat_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "item/generated",
	  "textures": {
		"layer0": `tfc:items/wood/boat/${woodType}`
	  }
	}
    let door_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "item/generated",
	  "textures": {
		"layer0": `tfc:items/wood/door/${woodType}`
	  }
	}
    let fence_gate_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "block/fence_gate_closed",
	  "textures": {
		"texture": `tfc:blocks/wood/planks/${woodType}`
	  }
	}
    let fence_gate_log_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "tfcflorae:block/wood/fence_gate/fence_gate_closed",
	  "textures": {
		"log": `tfc:blocks/wood/log/${woodType}`,
		"planks": `tfc:blocks/wood/planks/${woodType}`,
		"particle": `tfc:blocks/wood/log/${woodType}`
	  }
	}
    let fence_log_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "tfcflorae:block/wood/fence/fence_inventory",
	  "textures": {
		"top": `tfc:blocks/wood/top/${woodType}`,
		"log": `tfc:blocks/wood/log/${woodType}`,
		"planks": `tfc:blocks/wood/planks/${woodType}`,
		"particle": `tfc:blocks/wood/log/${woodType}`
	  }
	}
    let log_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "item/generated",
	  "textures": {
		"layer0": `tfc:items/wood/log/${woodType}`
	  }
	}
    let lumber_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "item/generated",
	  "textures": {
		"layer0": `tfc:items/wood/lumber/${woodType}`
	  }
	}
    let pole_itemJSON = {
	  "parent": "item/handheld",
	  "textures": {
		"layer0": `tfc:items/wood/pole/${woodType}`
	  }
	}
    let trapdoor_itemJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "block/trapdoor_bottom",
	  "textures": {
		"texture": `tfc:blocks/wood/trapdoor/${woodType}`
	  }
	}

    // Itemmodels  
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/boat/${woodType}.json`, JSON.stringify(boat_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/door/${woodType}.json`, JSON.stringify(door_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/fence_gate/${woodType}.json`, JSON.stringify(fence_gate_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/fence_gate_log/${woodType}.json`, JSON.stringify(fence_gate_log_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/fence_log/${woodType}.json`, JSON.stringify(fence_log_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/log/${woodType}.json`, JSON.stringify(log_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/lumber/${woodType}.json`, JSON.stringify(lumber_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/pole/${woodType}.json`, JSON.stringify(pole_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/bamboo/trapdoor/${woodType}.json`, JSON.stringify(trapdoor_itemJSON, null, 2))
}