const fs = require('fs');

    let MISC_FOOD_TYPES = {
    'allspice': 'allspice',
    'clove': 'clove',
    'curry_leaf': 'curry_leaf',
    'star_anise': 'star_anise',
    'liquorice_root': 'liquorice_root',
    'cassia_cinnamon_bark': 'cassia_cinnamon_bark',
    'ground_cassia_cinnamon': 'ground_cassia_cinnamon',
    'ceylon_cinnamon_bark': 'ceylon_cinnamon_bark',
    'ground_ceylon_cinnamon': 'ground_ceylon_cinnamon',
    'ground_black_pepper': 'ground_black_pepper',
    'black_tea': 'black_tea',
    'green_tea': 'green_tea',
    'white_tea': 'white_tea',
    'cannabis_bud': 'cannabis_bud',
    'cannabis_leaf': 'cannabis_leaf',
    'coca_leaf': 'coca_leaf',
    'opium_poppy_bulb': 'opium_poppy_bulb',
    'peyote': 'peyote',
    'tobacco_leaf': 'tobacco_leaf',
    'raw_eel': 'raw_eel',
    'cooked_eel': 'cooked_eel',
    'raw_crab': 'raw_crab',
    'cooked_crab': 'cooked_crab',
    'raw_clam': 'raw_clam',
    'cooked_clam': 'cooked_clam',
    'raw_scallop': 'raw_scallop',
    'cooked_scallop': 'cooked_scallop',
    'raw_starfish': 'raw_starfish',
    'cooked_starfish': 'cooked_starfish',
    'pumpkin': 'pumpkin',
    'melon': 'melon',
    'cocoa_beans': 'cocoa_beans',
    'roasted_cocoa_beans': 'roasted_cocoa_beans',
    'cocoa_powder': 'cocoa_powder',
    'cocoa_butter': 'cocoa_butter',
    'chocolate': 'chocolate',
    'roasted_coffee_beans': 'roasted_coffee_beans',
    'coffee_powder': 'coffee_powder',
    'amaranth': 'amaranth',
    'amaranth_grain': 'amaranth_grain',
    'amaranth_flour': 'amaranth_flour',
    'amaranth_dough': 'amaranth_dough',
    'amaranth_bread': 'amaranth_bread',
    'buckwheat': 'buckwheat',
    'buckwheat_grain': 'buckwheat_grain',
    'buckwheat_flour': 'buckwheat_flour',
    'buckwheat_dough': 'buckwheat_dough',
    'buckwheat_bread': 'buckwheat_bread',
    'fonio': 'fonio',
    'fonio_grain': 'fonio_grain',
    'fonio_flour': 'fonio_flour',
    'fonio_dough': 'fonio_dough',
    'fonio_bread': 'fonio_bread',
    'millet': 'millet',
    'millet_grain': 'millet_grain',
    'millet_flour': 'millet_flour',
    'millet_dough': 'millet_dough',
    'millet_bread': 'millet_bread',
    'quinoa': 'quinoa',
    'quinoa_grain': 'quinoa_grain',
    'quinoa_flour': 'quinoa_flour',
    'quinoa_dough': 'quinoa_dough',
    'quinoa_bread': 'quinoa_bread',
    'spelt': 'spelt',
    'spelt_grain': 'spelt_grain',
    'spelt_flour': 'spelt_flour',
    'spelt_dough': 'spelt_dough',
    'spelt_bread': 'spelt_bread',
    'wild_rice': 'wild_rice',
    'wild_rice_grain': 'wild_rice_grain',
    'wild_rice_flour': 'wild_rice_flour',
    'wild_rice_dough': 'wild_rice_dough',
    'wild_rice_bread': 'wild_rice_bread',
    'linseed': 'linseed',
    'rape_seed': 'rape_seed',
    'sunflower_seed': 'sunflower_seed',
    'opium_poppy_seed': 'opium_poppy_seed',
    'hash_muffin': 'hash_muffin',
    'rutabaga': 'rutabaga',
    'turnip': 'turnip',
    'mustard': 'mustard',
    'black_eyed_peas': 'black_eyed_peas',
    'green_cayenne_pepper': 'green_cayenne_pepper',
    'red_cayenne_pepper': 'red_cayenne_pepper',
    'ginger': 'ginger',
    'ginseng': 'ginseng',
    'celery': 'celery',
    'lettuce': 'lettuce',
    'peanut': 'peanut',
    'sweet_potato': 'sweet_potato',
    'sugar_beet': 'sugar_beet',
    'linseed_paste': 'linseed_paste',
    'rape_seed_paste': 'rape_seed_paste',
    'sunflower_seed_paste': 'sunflower_seed_paste',
    'opium_poppy_seed_paste': 'opium_poppy_seed_paste',
    'mashed_sugar_beet': 'mashed_sugar_beet',
    'mashed_sugar_cane': 'mashed_sugar_cane',
    'soybean_paste': 'soybean_paste',
    'cow_cheese': 'cow_cheese',
    'goat_cheese': 'goat_cheese',
    'sheep_cheese': 'sheep_cheese',
    'amaranth_bread_sandwich': 'amaranth_bread_sandwich',
    'buckwheat_bread_sandwich': 'buckwheat_bread_sandwich',
    'fonio_bread_sandwich': 'fonio_bread_sandwich',
    'millet_bread_sandwich': 'millet_bread_sandwich',
    'quinoa_bread_sandwich': 'quinoa_bread_sandwich',
    'spelt_bread_sandwich': 'spelt_bread_sandwich',
    'wild_rice_bread_sandwich': 'wild_rice_bread_sandwich',
    'roasted_coffea_cherries': 'roasted_coffea_cherries',
    'dark_chocolate': 'dark_chocolate',
    'milk_chocolate': 'milk_chocolate',
    'white_chocolate': 'white_chocolate',
    'pumpkin_scooped': 'pumpkin_scooped',
    'pumpkin_chunks': 'pumpkin_chunks'
    }

for(let miscFoodType of Object.keys(MISC_FOOD_TYPES))
{
    generateRecipes(miscFoodType)
}

function generateRecipes(miscFoodType)
{
    let miscFoodJSON = {
      "parent": "item/handheld",
      "textures": {
        "layer0": `tfcflorae:items/food/${miscFoodType}`
      }
    }
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/food/${miscFoodType}.json`, JSON.stringify(miscFoodJSON, null, 2))
}