const fs = require('fs');

let FRUIT_WOOD_TYPES = {
    'cassia_cinnamon': 'cassia_cinnamon',
    'ceylon_cinnamon': 'ceylon_cinnamon',
    'abiu': 'abiu',
    'allspice': 'allspice',
    'amla': 'amla',
    'apricot': 'apricot',
    'avocado': 'avocado',
    'bael': 'bael',
    'bay_laurel': 'bay_laurel',
    'ber': 'ber',
    'bergamot': 'bergamot',
    'black_cherry': 'black_cherry',
    'black_pepper': 'black_pepper',
    'blackcurrant': 'blackcurrant',
    'blackthorn': 'blackthorn',
    'buddha_hand': 'buddha_hand',
    'cacao': 'cacao',
    'cherry_plum': 'cherry_plum',
    'citron': 'citron',
    'coconut': 'coconut',
    'coffea': 'coffea',
    'crabapple': 'crabapple',
    'damson_plum': 'damson_plum',
    'date': 'date',
    'elder': 'elder',
    'elderberry': 'elderberry',
    'fig': 'fig',
    'finger_lime': 'finger_lime',
    'grapefruit': 'grapefruit',
    'guava': 'guava',
    'ice_cream_bean': 'ice_cream_bean',
    'jackfruit': 'jackfruit',
    'jujube': 'jujube',
    'juniper': 'juniper',
    'kaki': 'kaki',
    'key_lime': 'key_lime',
    'kluwak': 'kluwak',
    'kumquat': 'kumquat',
    'lime': 'lime',
    'longan': 'longan',
    'loquat': 'loquat',
    'lychee': 'lychee',
    'mamey_sapote': 'mamey_sapote',
    'manderin': 'manderin',
    'mango': 'mango',
    'mangosteen': 'mangosteen',
    'nectarine': 'nectarine',
    'ohia_ai': 'ohia_ai',
    'osage_orange': 'osage_orange',
    'papaya': 'papaya',
    'passion_fruit': 'passion_fruit',
    'pear': 'pear',
    'persimmon': 'persimmon',
    'persian_lime': 'persian_lime',
    'peruvian_pepper': 'peruvian_pepper',
    'plantain': 'plantain',
    'plum': 'plum',
    'pomegranate': 'pomegranate',
    'pomelo': 'pomelo',
    'quince': 'quince',
    'rainier_cherry': 'rainier_cherry',
    'red_banana': 'red_banana',
    'red_currant': 'red_currant',
    'sand_pear': 'sand_pear',
    'sapodilla': 'sapodilla',
    'satsuma': 'satsuma',
    'sour_cherry': 'sour_cherry',
    'soursop': 'soursop',
    'star_anise': 'star_anise',
    'starfruit': 'starfruit',
    'tamarillo': 'tamarillo',
    'tangerine': 'tangerine',
    'tropical_apricot': 'tropical_apricot',
    'wild_cherry': 'wild_cherry',
    'acorn': 'acorn',
    'almond': 'almond',
    'beechnut': 'beechnut',
    'black_walnut': 'black_walnut',
    'brazil_nut': 'brazil_nut',
    'breadnut': 'breadnut',
    'bunya': 'bunya',
    'butternut': 'butternut',
    'candlenut': 'candlenut',
    'cashew': 'cashew',
    'ginkgo': 'ginkgo',
    'hazelnut': 'hazelnut',
    'heartnut': 'heartnut',
    'hickory_nut': 'hickory_nut',
    'kola': 'kola',
    'kukui': 'kukui',
    'macadamia': 'macadamia',
    'mongongo': 'mongongo',
    'monkey_puzzle': 'monkey_puzzle',
    'nutmeg': 'nutmeg',
    'paradise_nut': 'paradise_nut',
    'pecan': 'pecan',
    'pine_nut': 'pine_nut',
    'pistachio': 'pistachio',
    'walnut': 'walnut',
    'banana': 'banana',
    'cherry': 'cherry',
    'olive': 'olive',
    'red_apple': 'red_apple',
    'green_apple': 'green_apple',
    'lemon': 'lemon',
    'orange': 'orange',
    'peach': 'peach',
    'plum': 'plum'
}


for(let woodType of Object.keys(FRUIT_WOOD_TYPES))
{
    generateRecipes(woodType)
}

function generateRecipes(woodType)
{
    let barrelJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:barrel",
          "textures": {
            "particle": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "planks": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "sheet": `tfcflorae:blocks/wood/fruit_tree/sheets/${woodType}`,
            "hoop": "tfc:blocks/barrelhoop"
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "sealed": {
            "true": {
              "model": "tfc:barrel_sealed"
            },
            "false": {}
          },
          "inventory": [
            {}
          ]
        }
      }
      let bookshelfJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:bookshelf",
          "textures": {
            "all": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "north": "tfc:blocks/wood/bookshelf",
            "south": "tfc:blocks/wood/bookshelf",
            "east": "tfc:blocks/wood/bookshelf",
            "west": "tfc:blocks/wood/bookshelf"
          }
        },
        "variants": {
          "normal": [
            {}
          ]
        }
      }
      let buttonJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "button",
          "textures": {
            "texture": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {
			  "model": "button_inventory"
		    }
          ],
          "powered": {
            "false": {},
            "true": {
              "model": "button_pressed"
            }
          },
          "facing": {
            "up": {},
            "down": {
              "x": 180
            },
            "east": {
              "x": 90,
              "y": 90
            },
            "west": {
              "x": 90,
              "y": 270
            },
            "south": {
              "x": 90,
              "y": 180
            },
            "north": {
              "x": 90
            }
          },
          "inventory": [
            {
              "model": "button_inventory"
            }
          ]
        }
      }
      let branchJSON = {
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:empty",
          "textures": {
            "texture": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "facing": {
            "up": {
              "submodel": "tfc:fruit_trees/branch_vertical"
            },
            "down": {
              "submodel": "tfc:fruit_trees/branch_vertical"
            },
            "north": {
              "submodel": "tfc:fruit_trees/branch_horizontal"
            },
            "east": {
              "submodel": "tfc:fruit_trees/branch_horizontal",
              "y": 90
            },
            "south": {
              "submodel": "tfc:fruit_trees/branch_horizontal",
              "y": 180
            },
            "west": {
              "submodel": "tfc:fruit_trees/branch_horizontal",
              "y": 270
            }
          },
          "north": {
            "0": {},
            "1": {"submodel": "tfc:fruit_trees/branch_vertical_connection"},
            "2": {"submodel": "tfc:fruit_trees/branch_horizontal_connection"}
          },
          "east": {
            "0": {},
            "1": {"submodel": "tfc:fruit_trees/branch_vertical_connection", "y": 90},
            "2": {"submodel": "tfc:fruit_trees/branch_horizontal_connection", "y": 90}
          },
          "south": {
            "0": {},
            "1": {"submodel": "tfc:fruit_trees/branch_vertical_connection", "y": 180},
            "2": {"submodel": "tfc:fruit_trees/branch_horizontal_connection", "y": 180}
          },
          "west": {
            "0": {},
            "1": {"submodel": "tfc:fruit_trees/branch_vertical_connection", "y": 270},
            "2": {"submodel": "tfc:fruit_trees/branch_horizontal_connection", "y": 270}
          },
          "up": {
            "0": {},
            "1": {},
            "2": {"submodel": "tfc:fruit_trees/branch_horizontal_connection", "x": 270}
          }
        }
      }
      let doorJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "textures": {
            "bottom": `tfcflorae:blocks/wood/fruit_tree/door/lower/${woodType}`,
            "top": `tfcflorae:blocks/wood/fruit_tree/door/upper/${woodType}`
          }
        },
        "variants": {
          "facing=east,half=lower,hinge=left,open=false": {
            "model": "door_bottom"
          },
          "facing=south,half=lower,hinge=left,open=false": {
            "model": "door_bottom",
            "y": 90
          },
          "facing=west,half=lower,hinge=left,open=false": {
            "model": "door_bottom",
            "y": 180
          },
          "facing=north,half=lower,hinge=left,open=false": {
            "model": "door_bottom",
            "y": 270
          },
          "facing=east,half=lower,hinge=right,open=false": {
            "model": "door_bottom_rh"
          },
          "facing=south,half=lower,hinge=right,open=false": {
            "model": "door_bottom_rh",
            "y": 90
          },
          "facing=west,half=lower,hinge=right,open=false": {
            "model": "door_bottom_rh",
            "y": 180
          },
          "facing=north,half=lower,hinge=right,open=false": {
            "model": "door_bottom_rh",
            "y": 270
          },
          "facing=east,half=lower,hinge=left,open=true": {
            "model": "door_bottom_rh",
            "y": 90
          },
          "facing=south,half=lower,hinge=left,open=true": {
            "model": "door_bottom_rh",
            "y": 180
          },
          "facing=west,half=lower,hinge=left,open=true": {
            "model": "door_bottom_rh",
            "y": 270
          },
          "facing=north,half=lower,hinge=left,open=true": {
            "model": "door_bottom_rh"
          },
          "facing=east,half=lower,hinge=right,open=true": {
            "model": "door_bottom",
            "y": 270
          },
          "facing=south,half=lower,hinge=right,open=true": {
            "model": "door_bottom"
          },
          "facing=west,half=lower,hinge=right,open=true": {
            "model": "door_bottom",
            "y": 90
          },
          "facing=north,half=lower,hinge=right,open=true": {
            "model": "door_bottom",
            "y": 180
          },
          "facing=east,half=upper,hinge=left,open=false": {
            "model": "tfc:door_top_tfc"
          },
          "facing=south,half=upper,hinge=left,open=false": {
            "model": "tfc:door_top_tfc",
            "y": 90
          },
          "facing=west,half=upper,hinge=left,open=false": {
            "model": "tfc:door_top_tfc",
            "y": 180
          },
          "facing=north,half=upper,hinge=left,open=false": {
            "model": "tfc:door_top_tfc",
            "y": 270
          },
          "facing=east,half=upper,hinge=right,open=false": {
            "model": "tfc:door_top_rh_tfc"
          },
          "facing=south,half=upper,hinge=right,open=false": {
            "model": "tfc:door_top_rh_tfc",
            "y": 90
          },
          "facing=west,half=upper,hinge=right,open=false": {
            "model": "tfc:door_top_rh_tfc",
            "y": 180
          },
          "facing=north,half=upper,hinge=right,open=false": {
            "model": "tfc:door_top_rh_tfc",
            "y": 270
          },
          "facing=east,half=upper,hinge=left,open=true": {
            "model": "tfc:door_top_rh_tfc",
            "y": 90
          },
          "facing=south,half=upper,hinge=left,open=true": {
            "model": "tfc:door_top_rh_tfc",
            "y": 180
          },
          "facing=west,half=upper,hinge=left,open=true": {
            "model": "tfc:door_top_rh_tfc",
            "y": 270
          },
          "facing=north,half=upper,hinge=left,open=true": {
            "model": "tfc:door_top_rh_tfc"
          },
          "facing=east,half=upper,hinge=right,open=true": {
            "model": "tfc:door_top_tfc",
            "y": 270
          },
          "facing=south,half=upper,hinge=right,open=true": {
            "model": "tfc:door_top_tfc"
          },
          "facing=west,half=upper,hinge=right,open=true": {
            "model": "tfc:door_top_tfc",
            "y": 90
          },
          "facing=north,half=upper,hinge=right,open=true": {
            "model": "tfc:door_top_tfc",
            "y": 180
          }
        }
      }
      let fenceJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "fence_post",
		"textures": {
		  "texture": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "fence_inventory"
		  }
		],
		"inventory": {
		  "model": "fence_inventory"
		},
		"north": {
		  "true": {
			"submodel": "fence_side"
		  },
		  "false": {}
		},
		"east": {
		  "true": {
			"submodel": "fence_side",
			"y": 90
		  },
		  "false": {}
		},
		"south": {
		  "true": {
			"submodel": "fence_side",
			"y": 180
		  },
		  "false": {}
		},
		"west": {
		  "true": {
			"submodel": "fence_side",
			"y": 270
		  },
		  "false": {}
		}
	  }
	}
      let fence_gateJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "fence_gate_closed",
		"textures": {
		  "texture": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
		},
		"uvlock": true
	  },
	  "variants": {
		"normal": [
		  {
			"model": "fence_gate_closed"
		  }
		],
		"facing=south,in_wall=false,open=false": {
		  "model": "fence_gate_closed"
		},
		"facing=west,in_wall=false,open=false": {
		  "model": "fence_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=false,open=false": {
		  "model": "fence_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=false,open=false": {
		  "model": "fence_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=false,open=true": {
		  "model": "fence_gate_open"
		},
		"facing=west,in_wall=false,open=true": {
		  "model": "fence_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=false,open=true": {
		  "model": "fence_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=false,open=true": {
		  "model": "fence_gate_open",
		  "y": 270
		},
		"facing=south,in_wall=true,open=false": {
		  "model": "wall_gate_closed"
		},
		"facing=west,in_wall=true,open=false": {
		  "model": "wall_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=true,open=false": {
		  "model": "wall_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=true,open=false": {
		  "model": "wall_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=true,open=true": {
		  "model": "wall_gate_open"
		},
		"facing=west,in_wall=true,open=true": {
		  "model": "wall_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=true,open=true": {
		  "model": "wall_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=true,open=true": {
		  "model": "wall_gate_open",
		  "y": 270
		}
	  }
	}
      let fence_logJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfcflorae:wood/fence/fence_post",
		"textures": {
		  "top": `tfcflorae:blocks/wood/fruit_tree/top/${woodType}`,
		  "log": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`,
		  "planks": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
		  "particle": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "tfcflorae:wood/fence/fence_inventory"
		  }
		],
		"inventory": {
		  "model": "tfcflorae:wood/fence/fence_inventory"
		},
		"north": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side"
		  },
		  "false": {}
		},
		"east": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side",
			"y": 90
		  },
		  "false": {}
		},
		"south": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side",
			"y": 180
		  },
		  "false": {}
		},
		"west": {
		  "true": {
			"submodel": "tfcflorae:wood/fence/fence_side",
			"y": 270
		  },
		  "false": {}
		}
	  }
	}
      let fence_gate_logJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		"textures": {
		  "log": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`,
		  "planks": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
		  "particle": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`
		},
		"uvlock": true
	  },
	  "variants": {
		"normal": [
		  {
			"model": "tfcflorae:wood/fence_gate/fence_gate_closed"
		  }
		],
		"facing=south,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed"
		},
		"facing=west,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=false,open=false": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open"
		},
		"facing=west,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=false,open=true": {
		  "model": "tfcflorae:wood/fence_gate/fence_gate_open",
		  "y": 270
		},
		"facing=south,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed"
		},
		"facing=west,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed",
		  "y": 90
		},
		"facing=north,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed",
		  "y": 180
		},
		"facing=east,in_wall=true,open=false": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_closed",
		  "y": 270
		},
		"facing=south,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open"
		},
		"facing=west,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open",
		  "y": 90
		},
		"facing=north,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open",
		  "y": 180
		},
		"facing=east,in_wall=true,open=true": {
		  "model": "tfcflorae:wood/fence_gate/wall_gate_open",
		  "y": 270
		}
	  }
	}
      let leavesJSON = {
        "forge_marker": 1,
        "defaults": {
          "model": "leaves",
          "textures": {
            "all": `tfcflorae:blocks/wood/fruit_tree/leaves/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "inventory": {
            "model": "leaves",
            "transform": "forge:default-block"
          },
          "state": {
            "normal": {
              "model": "leaves"
            },
            "flowering": {
              "model": "leaves",
              "textures": {
                "all": `tfcflorae:blocks/wood/fruit_tree/leaves${woodType}`,
                "texture": `tfcflorae:blocks/wood/fruit_tree/flowers/${woodType}`
              },
              "submodel": "tfc:fruit_trees/leaves_overlay"
            },
            "fruit": {
              "model": "leaves",
              "textures": {
                "all": `tfcflorae:blocks/wood/fruit_tree/leaves/${woodType}`,
                "texture": `tfcflorae:blocks/wood/fruit_tree/fruit/${woodType}`
              },
              "submodel": "tfc:fruit_trees/leaves_overlay"
            }
          }
        }
      }
      let planksJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "cube_all",
          "textures": {
            "all": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ]
        }
      }
      let saplingJSON = {
        "forge_marker": 1,
        "defaults": {
          "model": "cross",
          "textures": {
            "cross": `tfcflorae:blocks/wood/fruit_tree/sapling/${woodType}`,
            "layer0": `tfcflorae:blocks/wood/fruit_tree/sapling/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "inventory": {
            "model": "builtin/generated",
            "transform": "forge:default-item"
          }
        }
      }
      let loomJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:loom",
          "textures": {
            "texture": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "facing": {
            "south": {},
            "west": {
              "y": 90
            },
            "north": {
              "y": 180
            },
            "east": {
              "y": 270
            }
          }
        }
      }
      let supportJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:support/vertical",
          "textures": {
            "texture": `tfcflorae:blocks/wood/fruit_tree/sheets/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/sheets/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "inventory": {
            "model": "tfc:support/inventory"
          },
          "axis": {
            "y": {
              "model": "tfc:support/vertical"
            },
            "x": {
              "model": "tfc:support/horizontal"
            },
            "z": {
              "model": "tfc:support/horizontal"
            }
          },
          "north": {
            "true": {
              "submodel": "tfc:support/connection",
              "y": 270
            },
            "false": {}
          },
          "east": {
            "true": {
              "submodel": "tfc:support/connection"
            },
            "false": {}
          },
          "south": {
            "true": {
              "submodel": "tfc:support/connection",
              "y": 90
            },
            "false": {}
          },
          "west": {
            "true": {
              "submodel": "tfc:support/connection",
              "y": 180
            },
            "false": {}
          }
        }
      }
      let tool_rackJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:tool_rack",
          "textures": {
            "texture": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "facing": {
            "south": {},
            "west": {
              "y": 90
            },
            "north": {
              "y": 180
            },
            "east": {
              "y": 270
            }
          }
        }
      }
      let trapdoorJSON = {
        "forge_marker": 1,
        "defaults": {
          "textures": {
            "texture": `tfcflorae:blocks/wood/fruit_tree/trapdoor/${woodType}`
          }
        },
        "variants": {
          "facing=north,half=bottom,open=false": {"model": "wooden_trapdoor_bottom"},
          "facing=south,half=bottom,open=false": {"model": "wooden_trapdoor_bottom", "y": 180},
          "facing=east,half=bottom,open=false": {"model": "wooden_trapdoor_bottom", "y": 90},
          "facing=west,half=bottom,open=false": {"model": "wooden_trapdoor_bottom", "y": 270},
          "facing=north,half=top,open=false": {"model": "wooden_trapdoor_top"},
          "facing=south,half=top,open=false": {"model": "wooden_trapdoor_top", "y": 180},
          "facing=east,half=top,open=false": {"model": "wooden_trapdoor_top", "y": 90},
          "facing=west,half=top,open=false": {"model": "wooden_trapdoor_top", "y": 270},
          "facing=north,half=bottom,open=true": {"model": "wooden_trapdoor_open"},
          "facing=south,half=bottom,open=true": {"model": "wooden_trapdoor_open", "y": 180},
          "facing=east,half=bottom,open=true": {"model": "wooden_trapdoor_open", "y": 90},
          "facing=west,half=bottom,open=true": {"model": "wooden_trapdoor_open", "y": 270},
          "facing=north,half=top,open=true": {"model": "wooden_trapdoor_open"},
          "facing=south,half=top,open=true": {"model": "wooden_trapdoor_open", "y": 180},
          "facing=east,half=top,open=true": {"model": "wooden_trapdoor_open", "y": 90},
          "facing=west,half=top,open=true": {"model": "wooden_trapdoor_open", "y": 270}
        }
      }
      let trunkJSON = {
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:fruit_trees/trunk",
          "textures": {
            "texture": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "north": {
            "true": {
              "submodel": "tfc:fruit_trees/trunk_connection"
            },
            "false": {}
          },
          "east": {
            "true": {
              "submodel": "tfc:fruit_trees/trunk_connection",
              "y": 90
            },
            "false": {}
          },
          "south": {
            "true": {
              "submodel": "tfc:fruit_trees/trunk_connection",
              "y": 180
            },
            "false": {}
          },
          "west": {
            "true": {
              "submodel": "tfc:fruit_trees/trunk_connection",
              "y": 270
            },
            "false": {}
          }
        }
      }
      let workbenchJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "tfc:workbench",
          "textures": {
            "all": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "particle": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "top": "tfc:blocks/wood/workbench_top",
            "north": "tfc:blocks/wood/workbench_front",
            "south": "tfc:blocks/wood/workbench_front",
            "east": "tfc:blocks/wood/workbench_side",
            "west": "tfc:blocks/wood/workbench_side"
          }
        },
        "variants": {
          "normal": [
            {}
          ]
        }
      }
      let doubleslabJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "cube_all",
          "textures": {
            "all": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
          }
        },
        "variants": {
          "normal": [
            {}
          ]
        }
      }
      let slabJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "model": "half_slab",
          "textures": {
            "top": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "bottom": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "side": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
          }
        },
        "variants": {
          "normal": [
            {}
          ],
          "half": {
            "bottom": {},
            "top": {
              "model": "upper_slab"
            }
          }
        }
      }
      let stairsJSON = {
        "__comment": "Generated by generateResources.py function: blockstate",
        "forge_marker": 1,
        "defaults": {
          "textures": {
            "top": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "bottom": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
            "side": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
          },
          "uvlock": true
        },
        "variants": {
          "normal": {
            "model": "stairs"
          },
          "facing=east,half=bottom,shape=straight": {
            "model": "stairs"
          },
          "facing=west,half=bottom,shape=straight": {
            "model": "stairs",
            "y": 180
          },
          "facing=south,half=bottom,shape=straight": {
            "model": "stairs",
            "y": 90
          },
          "facing=north,half=bottom,shape=straight": {
            "model": "stairs",
            "y": 270
          },
          "facing=east,half=bottom,shape=outer_right": {
            "model": "outer_stairs"
          },
          "facing=west,half=bottom,shape=outer_right": {
            "model": "outer_stairs",
            "y": 180
          },
          "facing=south,half=bottom,shape=outer_right": {
            "model": "outer_stairs",
            "y": 90
          },
          "facing=north,half=bottom,shape=outer_right": {
            "model": "outer_stairs",
            "y": 270
          },
          "facing=east,half=bottom,shape=outer_left": {
            "model": "outer_stairs",
            "y": 270
          },
          "facing=west,half=bottom,shape=outer_left": {
            "model": "outer_stairs",
            "y": 90
          },
          "facing=south,half=bottom,shape=outer_left": {
            "model": "outer_stairs"
          },
          "facing=north,half=bottom,shape=outer_left": {
            "model": "outer_stairs",
            "y": 180
          },
          "facing=east,half=bottom,shape=inner_right": {
            "model": "inner_stairs"
          },
          "facing=west,half=bottom,shape=inner_right": {
            "model": "inner_stairs",
            "y": 180
          },
          "facing=south,half=bottom,shape=inner_right": {
            "model": "inner_stairs",
            "y": 90
          },
          "facing=north,half=bottom,shape=inner_right": {
            "model": "inner_stairs",
            "y": 270
          },
          "facing=east,half=bottom,shape=inner_left": {
            "model": "inner_stairs",
            "y": 270
          },
          "facing=west,half=bottom,shape=inner_left": {
            "model": "inner_stairs",
            "y": 90
          },
          "facing=south,half=bottom,shape=inner_left": {
            "model": "inner_stairs"
          },
          "facing=north,half=bottom,shape=inner_left": {
            "model": "inner_stairs",
            "y": 180
          },
          "facing=east,half=top,shape=straight": {
            "model": "stairs",
            "x": 180
          },
          "facing=west,half=top,shape=straight": {
            "model": "stairs",
            "x": 180,
            "y": 180
          },
          "facing=south,half=top,shape=straight": {
            "model": "stairs",
            "x": 180,
            "y": 90
          },
          "facing=north,half=top,shape=straight": {
            "model": "stairs",
            "x": 180,
            "y": 270
          },
          "facing=east,half=top,shape=outer_right": {
            "model": "outer_stairs",
            "x": 180,
            "y": 90
          },
          "facing=west,half=top,shape=outer_right": {
            "model": "outer_stairs",
            "x": 180,
            "y": 270
          },
          "facing=south,half=top,shape=outer_right": {
            "model": "outer_stairs",
            "x": 180,
            "y": 180
          },
          "facing=north,half=top,shape=outer_right": {
            "model": "outer_stairs",
            "x": 180
          },
          "facing=east,half=top,shape=outer_left": {
            "model": "outer_stairs",
            "x": 180
          },
          "facing=west,half=top,shape=outer_left": {
            "model": "outer_stairs",
            "x": 180,
            "y": 180
          },
          "facing=south,half=top,shape=outer_left": {
            "model": "outer_stairs",
            "x": 180,
            "y": 90
          },
          "facing=north,half=top,shape=outer_left": {
            "model": "outer_stairs",
            "x": 180,
            "y": 270
          },
          "facing=east,half=top,shape=inner_right": {
            "model": "inner_stairs",
            "x": 180,
            "y": 90
          },
          "facing=west,half=top,shape=inner_right": {
            "model": "inner_stairs",
            "x": 180,
            "y": 270
          },
          "facing=south,half=top,shape=inner_right": {
            "model": "inner_stairs",
            "x": 180,
            "y": 180
          },
          "facing=north,half=top,shape=inner_right": {
            "model": "inner_stairs",
            "x": 180
          },
          "facing=east,half=top,shape=inner_left": {
            "model": "inner_stairs",
            "x": 180
          },
          "facing=west,half=top,shape=inner_left": {
            "model": "inner_stairs",
            "x": 180,
            "y": 180
          },
          "facing=south,half=top,shape=inner_left": {
            "model": "inner_stairs",
            "x": 180,
            "y": 90
          },
          "facing=north,half=top,shape=inner_left": {
            "model": "inner_stairs",
            "x": 180,
            "y": 270
          }
        }
      }
      let pressureplateJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "pressure_plate",
		"textures": {
		  "texture": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
		  "particle": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {
			"model": "stone_pressure_plate_up"
		  }
		],
		"powered": {
		  "false": {
			"model": "stone_pressure_plate_up"
		  },
		  "true": {
			"model": "stone_pressure_plate_down"
		  }
		},
		"inventory": [
		  {
			"model": "stone_pressure_plate_up"
		  }
		]
	  }
	}
	  
      // Items
      let itemFruitBoatJSON = {
        "__comment": "Generated by generateResources.py function: model",
        "parent": "item/generated",
        "textures": {
          "layer0": `tfcflorae:items/wood/fruit_tree/boat/${woodType}`
        }
      }
      let itemFruitDoorJSON = {
        "__comment": "Generated by generateResources.py function: model",
        "parent": "item/generated",
        "textures": {
          "layer0": `tfcflorae:items/wood/fruit_tree/door/${woodType}`
        }
      }
      let itemFruitFenceGateJSON = {
        "__comment": "Generated by generateResources.py function: model",
        "parent": "block/fence_gate_closed",
        "textures": {
          "texture": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`
        }
      }
      let itemFruitLogJSON = {
        "__comment": "Generated by generateResources.py function: model",
        "parent": "item/generated",
        "textures": {
          "layer0": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`
        }
      }
      let itemFruitLumberJSON = {
        "__comment": "Generated by generateResources.py function: model",
        "parent": "item/generated",
        "textures": {
          "layer0": `tfcflorae:blocks/wood/fruit_tree/lumber/${woodType}`
        }
      }
      let itemFruitTrapdoorJSON = {
        "__comment": "Generated by generateResources.py function: model",
        "parent": "block/trapdoor_bottom",
        "textures": {
          "texture": `tfcflorae:blocks/wood/fruit_tree/trapdoor/${woodType}`
        }
      }
      let itemFruitTreePoleJSON = {
        "parent": "item/handheld",
        "textures": {
          "layer0": `tfcflorae:items/wood/fruit_tree/pole/${woodType}`
        }
      }
      let itemFruitTreeLumberJSON = {
        "parent": "item/handheld",
        "textures": {
          "layer0": `tfcflorae:items/wood/fruit_tree/lumber/${woodType}`
        }
      }
      let itemFruitTreeFenceGateLogJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "tfcflorae:block/wood/fence_gate/fence_gate_closed",
	  "textures": {
		"log": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`,
		"planks": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
		"particle": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`
	    }
	  }
      let itemFruitTreeFenceLogJSON = {
	  "__comment": "Generated by generateResources.py function: model",
	  "parent": "tfcflorae:block/wood/fence/fence_inventory",
	  "textures": {
		"top": `tfcflorae:blocks/wood/fruit_tree/top/${woodType}`,
		"log": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`,
		"planks": `tfcflorae:blocks/wood/fruit_tree/planks/${woodType}`,
		"particle": `tfcflorae:blocks/wood/fruit_tree/log/${woodType}`
		}
	  }
	// Recipes
    let BarrelRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"X X",
		"X X",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/barrel/${woodType}`,
		"data": 0,
		"count": 1
	  }
	}
    let BoatRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"   ",
		"X X",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/boat/${woodType}`,
		"count": 1
	  }
	}
    let BookshelfRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX",
		"BBB",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		},
		"B": {
		  "item": "minecraft:book"
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/bookshelf/${woodType}`,
		"count": 1
	  }
	}
    let ButtonRecipe = {
	  "type": "minecraft:crafting_shapeless",
	  "ingredients": [
		{
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  ],
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/button/${woodType}`,
		"count": 1
	  }
	}
    let ChestRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX",
		"X X",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/chest/${woodType}`,
		"count": 1
	  }
	}
    let ChestLumberRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX",
		"X X",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/chest/${woodType}`,
		"count": 1
	  }
	}
    let ChestTrappedRecipe = {
	  "type": "minecraft:crafting_shapeless",
	  "ingredients": [
		{
		  "item": `tfcflorae:wood/fruit_tree/chest/${woodType}`
		},
		{
		  "item": "minecraft:tripwire_hook"
		}
	  ],
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/chest_trap/${woodType}`,
		"count": 1
	  }
	}
    let DoorRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XX",
		"XX",
		"XX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/door/${woodType}`,
		"count": 2
	  }
	}
    let FenceRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XBX",
		"XBX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		},
		"B": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/fence/${woodType}`,
		"count": 8
	  }
	}
    let FenceGateRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"BXB",
		"BXB"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		},
		"B": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/fence_gate/${woodType}`,
		"count": 2
	  }
	}
    let LoomRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX",
		"XSX",
		"X X"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		},
		"S": {
		  "type": "forge:ore_dict",
		  "ore": "stickWood"
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/loom/${woodType}`,
		"count": 1
	  }
	}
    let LumberLogRecipe = {
	  "type": "tfc:damage_item_shapeless",
	  "ingredients": [
		{
		  "item": `tfcflorae:wood/fruit_tree/log/${woodType}`
		},
		{
		  "type": "forge:ore_dict",
		  "ore": "saw"
		}
	  ],
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`,
		"count": 8
	  }
	}
    let LumberPlanksRecipe = {
	  "type": "tfc:damage_item_shapeless",
	  "ingredients": [
		{
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		},
		{
		  "type": "forge:ore_dict",
		  "ore": "saw"
		}
	  ],
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`,
		"count": 4
	  }
	}
    let PlanksRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XX",
		"XX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/planks/${woodType}`,
		"count": 1
	  }
	}
    let PressurePlateRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/pressure_plate/${woodType}`,
		"count": 1
	  }
	}
    let SlabRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "result": {
		"item": `tfc:slab/fruit_tree/wood/${woodType}`,
		"data": 0,
		"count": 6
	  }
	}
    let StairsRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"X  ",
		"XX ",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "result": {
		"item": `tfc:stairs/fruit_tree/wood/${woodType}`,
		"count": 8
	  }
	}
    let SupportRecipe = {
	  "type": "tfc:damage_item_shaped",
	  "pattern": [
		"XB",
		" B"
	  ],
	  "key": {
		"X": {
		  "type": "forge:ore_dict",
		  "ore": "saw"
		},
		"B": {
		  "item": `tfcflorae:wood/fruit_tree/log/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/support/${woodType}`,
		"count": 8
	  }
	}
    let ToolRackRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX",
		"   ",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/tool_rack/${woodType}`,
		"count": 1
	  }
	}
    let TrapdoorRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XXX",
		"XXX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/trapdoor/${woodType}`,
		"count": 4
	  }
	}
    let WorkbenchRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XX",
		"XX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/planks/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/workbench/${woodType}`,
		"count": 1
	  }
	}
    let LumberPoleRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XX",
		"XX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/pole/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`,
		"count": 8
	  }
	}
    let FenceLogRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XBX",
		"XBX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/log/${woodType}`
		},
		"B": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/fence_log/${woodType}`,
		"count": 8
	  }
	}
    let FenceGateLogRecipe = {
	  "type": "minecraft:crafting_shaped",
	  "pattern": [
		"XBX",
		"XBX"
	  ],
	  "key": {
		"X": {
		  "item": `tfcflorae:wood/fruit_tree/lumber/${woodType}`
		},
		"B": {
		  "item": `tfcflorae:wood/fruit_tree/pole/${woodType}`
		}
	  },
	  "result": {
		"item": `tfcflorae:wood/fruit_tree/fence_gate_log/${woodType}`,
		"count": 8
	  }
	}
    let ChestJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:chest",
		"textures": {
		  "texture": `tfcflorae:entity/wood/fruit_tree/chests/chest/${woodType}`,
		  "particle": `tfcflorae:entity/wood/fruit_tree/chests/chest/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}
    let ChestTrapJSON = {
	  "__comment": "Generated by generateResources.py function: blockstate",
	  "forge_marker": 1,
	  "defaults": {
		"model": "tfc:chest",
		"textures": {
		  "texture": `tfcflorae:entity/wood/fruit_tree/chests/chest_trap/${woodType}`,
		  "particle": `tfcflorae:entity/wood/fruit_tree/chests/chest_trap/${woodType}`
		}
	  },
	  "variants": {
		"normal": [
		  {}
		]
	  }
	}

    // Blockmodels  
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/barrel/${woodType}.json`, JSON.stringify(barrelJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/bookshelf/${woodType}.json`, JSON.stringify(bookshelfJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/branch/${woodType}.json`, JSON.stringify(branchJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/button/${woodType}.json`, JSON.stringify(buttonJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/door/${woodType}.json`, JSON.stringify(doorJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/fence/${woodType}.json`, JSON.stringify(fenceJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/fence_gate/${woodType}.json`, JSON.stringify(fence_gateJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/fence_log/${woodType}.json`, JSON.stringify(fence_logJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/fence_gate_log/${woodType}.json`, JSON.stringify(fence_gate_logJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/leaves/${woodType}.json`, JSON.stringify(leavesJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/planks/${woodType}.json`, JSON.stringify(planksJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/sapling/${woodType}.json`, JSON.stringify(saplingJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/loom/${woodType}.json`, JSON.stringify(loomJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/support/${woodType}.json`, JSON.stringify(supportJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/tool_rack/${woodType}.json`, JSON.stringify(tool_rackJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/trapdoor/${woodType}.json`, JSON.stringify(trapdoorJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/trunk/${woodType}.json`, JSON.stringify(trunkJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/workbench/${woodType}.json`, JSON.stringify(workbenchJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/double_slab/${woodType}.json`, JSON.stringify(doubleslabJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/slab/${woodType}.json`, JSON.stringify(slabJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/stairs/${woodType}.json`, JSON.stringify(stairsJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/pressure_plate/${woodType}.json`, JSON.stringify(pressureplateJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/chest/${woodType}.json`, JSON.stringify(ChestJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/wood/fruit_tree/chest_trap/${woodType}.json`, JSON.stringify(ChestTrapJSON, null, 2))

    // Item Models
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/boat/${woodType}.json`, JSON.stringify(itemFruitBoatJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/door/${woodType}.json`, JSON.stringify(itemFruitDoorJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/fence_gate/${woodType}.json`, JSON.stringify(itemFruitFenceGateJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/log/${woodType}.json`, JSON.stringify(itemFruitLogJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/lumber/${woodType}.json`, JSON.stringify(itemFruitLumberJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/trapdoor/${woodType}.json`, JSON.stringify(itemFruitTrapdoorJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/fence_gate_log/${woodType}.json`, JSON.stringify(itemFruitTreeFenceGateLogJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/fence_log/${woodType}.json`, JSON.stringify(itemFruitTreeFenceLogJSON, null, 2))

    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/pole/${woodType}.json`, JSON.stringify(itemFruitTreePoleJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/wood/fruit_tree/lumber/${woodType}.json`, JSON.stringify(itemFruitTreeLumberJSON, null, 2))
	
	// Recipes
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/barrel/${woodType}.json`, JSON.stringify(BarrelRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/boat/${woodType}.json`, JSON.stringify(BoatRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/bookshelf/${woodType}.json`, JSON.stringify(BookshelfRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/button/${woodType}.json`, JSON.stringify(ButtonRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/chest/${woodType}.json`, JSON.stringify(ChestRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/chest_lumber/${woodType}.json`, JSON.stringify(ChestLumberRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/chest_trapped/${woodType}.json`, JSON.stringify(ChestTrappedRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/door/${woodType}.json`, JSON.stringify(DoorRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/fence/${woodType}.json`, JSON.stringify(FenceRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/fence_gate/${woodType}.json`, JSON.stringify(FenceGateRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/fence_log/${woodType}.json`, JSON.stringify(itemFruitTreeLumberJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/fence_gate_log/${woodType}.json`, JSON.stringify(itemFruitTreeLumberJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/loom/${woodType}.json`, JSON.stringify(LoomRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/lumber_log/${woodType}.json`, JSON.stringify(LumberLogRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/lumber_planks/${woodType}.json`, JSON.stringify(LumberPlanksRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/planks/${woodType}.json`, JSON.stringify(PlanksRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/pressure_plate/${woodType}.json`, JSON.stringify(PressurePlateRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/slab/${woodType}.json`, JSON.stringify(SlabRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/stairs/${woodType}.json`, JSON.stringify(StairsRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/support/${woodType}.json`, JSON.stringify(SupportRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/tool_rack/${woodType}.json`, JSON.stringify(ToolRackRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/trapdoor/${woodType}.json`, JSON.stringify(TrapdoorRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/workbench/${woodType}.json`, JSON.stringify(WorkbenchRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/lumber_pole/${woodType}.json`, JSON.stringify(LumberPoleRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/fence_log/${woodType}.json`, JSON.stringify(FenceLogRecipe, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/recipes/wood/fruit_tree/fence_gate_log/${woodType}.json`, JSON.stringify(FenceGateLogRecipe, null, 2))
}