const fs = require('fs');

let FLUID_TYPES = {
  'distilled_water': 'distilled_water',
  'waste': 'waste',
  'base_potash_liquor': 'base_potash_liquor',
  'white_tea': 'white_tea',
  'green_tea': 'green_tea',
  'black_tea': 'black_tea',
  'chamomile_tea': 'chamomile_tea',
  'dandelion_tea': 'dandelion_tea',
  'labrador_tea': 'labrador_tea',
  'coffee': 'coffee',
  'firma_cola': 'firma_cola',
  'agave_wine': 'agave_wine',
  'barley_wine': 'barley_wine',
  'banana_wine': 'banana_wine',
  'berry_wine': 'berry_wine',
  'cherry_wine': 'cherry_wine',
  'juniper_wine': 'juniper_wine',
  'lemon_wine': 'lemon_wine',
  'orange_wine': 'orange_wine',
  'papaya_wine': 'papaya_wine',
  'peach_wine': 'peach_wine',
  'pear_wine': 'pear_wine',
  'plum_wine': 'plum_wine',
  'mead': 'mead',
  'red_wine': 'red_wine',
  'wheat_wine': 'wheat_wine',
  'white_wine': 'white_wine',
  'calvados': 'calvados',
  'gin': 'gin',
  'tequila': 'tequila',
  'shochu': 'shochu',
  'banana_brandy': 'banana_brandy',
  'cherry_brandy': 'cherry_brandy',
  'lemon_brandy': 'lemon_brandy',
  'orange_brandy': 'orange_brandy',
  'papaya_brandy': 'papaya_brandy',
  'peach_brandy': 'peach_brandy',
  'pear_brandy': 'pear_brandy',
  'plum_brandy': 'plum_brandy',
  'berry_brandy': 'berry_brandy',
  'brandy': 'brandy',
  'cognac': 'cognac',
  'grappa': 'grappa',
  'beer_barley': 'beer_barley',
  'beer_corn': 'beer_corn',
  'beer_rye': 'beer_rye',
  'beer_wheat': 'beer_wheat',
  'beer_amaranth': 'beer_amaranth',
  'beer_buckwheat': 'beer_buckwheat',
  'beer_fonio': 'beer_fonio',
  'beer_millet': 'beer_millet',
  'beer_quinoa': 'beer_quinoa',
  'beer_spelt': 'beer_spelt',
  'sugar_water': 'sugar_water',
  'honey_water': 'honey_water',
  'rice_water': 'rice_water',
  'soybean_water': 'soybean_water',
  'linseed_water': 'linseed_water',
  'rape_seed_water': 'rape_seed_water',
  'sunflower_seed_water': 'sunflower_seed_water',
  'opium_poppy_seed_water': 'opium_poppy_seed_water',
  'sugar_beet_water': 'sugar_beet_water',
  'soy_milk': 'soy_milk',
  'linseed_oil': 'linseed_oil',
  'rape_seed_oil': 'rape_seed_oil',
  'sunflower_seed_oil': 'sunflower_seed_oil',
  'opium_poppy_seed_oil': 'opium_poppy_seed_oil',
  'wort': 'wort',
  'juice_blackberry': 'juice_blackberry',
  'juice_blueberry': 'juice_blueberry',
  'juice_bunch_berry': 'juice_bunch_berry',
  'juice_cloud_berry': 'juice_cloud_berry',
  'juice_cranberry': 'juice_cranberry',
  'juice_elderberry': 'juice_elderberry',
  'juice_gooseberry': 'juice_gooseberry',
  'juice_raspberry': 'juice_raspberry',
  'juice_snow_berry': 'juice_snow_berry',
  'juice_strawberry': 'juice_strawberry',
  'juice_wintergreen_berry': 'juice_wintergreen_berry',
  'juice_agave': 'juice_agave',
  'juice_apple': 'juice_apple',
  'juice_banana': 'juice_banana',
  'juice_cherry': 'juice_cherry',
  'juice_green_grape': 'juice_green_grape',
  'juice_juniper': 'juice_juniper',
  'juice_lemon': 'juice_lemon',
  'juice_orange': 'juice_orange',
  'juice_papaya': 'juice_papaya',
  'juice_peach': 'juice_peach',
  'juice_pear': 'juice_pear',
  'juice_plum': 'juice_plum',
  'juice_purple_grape': 'juice_purple_grape',
  'juice_barrel_cactus': 'juice_barrel_cactus'
}


for(let fluidType of Object.keys(FLUID_TYPES))
{
  generateFluids(fluidType)
}

function generateFluids(fluidType)
{
    let fluidsJSON = {
      "__comment": "Generated by generateResources.py function: blockstate",
      "forge_marker": 1,
      "defaults": {
        "model": "forge:fluid",
        "textures": {}
      },
      "variants": {
        "normal": {
          "transform": "forge:default-item",
          "custom": {
            "fluid": `${fluidType}`
          }
        }
      }
    }

    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/blockstates/fluid/${fluidType}.json`, JSON.stringify(fluidsJSON, null, 2))
}
