const fs = require('fs');

let FRUIT_WOOD_TYPES = {
    'abiu': 'abiu',
    'amla': 'amla',
    'apricot': 'apricot',
    'avocado': 'avocado',
    'bael': 'bael',
    'bay_laurel': 'bay_laurel',
    'ber': 'ber',
    'bergamot': 'bergamot',
    'black_cherry': 'black_cherry',
    'black_pepper': 'black_pepper',
    'blackcurrant': 'blackcurrant',
    'blackthorn': 'blackthorn',
    'buddha_hand': 'buddha_hand',
    'cacao': 'cacao',
    'cherry_plum': 'cherry_plum',
    'citron': 'citron',
    'coconut': 'coconut',
    'coffea': 'coffea',
    'crabapple': 'crabapple',
    'damson_plum': 'damson_plum',
    'date': 'date',
    'elder': 'elder',
    'elderberry': 'elderberry',
    'fig': 'fig',
    'finger_lime': 'finger_lime',
    'grapefruit': 'grapefruit',
    'guava': 'guava',
    'ice_cream_bean': 'ice_cream_bean',
    'jackfruit': 'jackfruit',
    'jujube': 'jujube',
    'juniper': 'juniper',
    'kaki': 'kaki',
    'key_lime': 'key_lime',
    'kluwak': 'kluwak',
    'kumquat': 'kumquat',
    'lime': 'lime',
    'longan': 'longan',
    'loquat': 'loquat',
    'lychee': 'lychee',
    'mamey_sapote': 'mamey_sapote',
    'manderin': 'manderin',
    'mango': 'mango',
    'mangosteen': 'mangosteen',
    'nectarine': 'nectarine',
    'ohia_ai': 'ohia_ai',
    'osage_orange': 'osage_orange',
    'papaya': 'papaya',
    'passion_fruit': 'passion_fruit',
    'pear': 'pear',
    'persimmon': 'persimmon',
    'persian_lime': 'persian_lime',
    'peruvian_pepper': 'peruvian_pepper',
    'plantain': 'plantain',
    'plum': 'plum',
    'pomegranate': 'pomegranate',
    'pomelo': 'pomelo',
    'quince': 'quince',
    'rainier_cherry': 'rainier_cherry',
    'red_banana': 'red_banana',
    'red_currant': 'red_currant',
    'sand_pear': 'sand_pear',
    'sapodilla': 'sapodilla',
    'satsuma': 'satsuma',
    'sour_cherry': 'sour_cherry',
    'soursop': 'soursop',
    'star_anise': 'star_anise',
    'starfruit': 'starfruit',
    'tamarillo': 'tamarillo',
    'tangerine': 'tangerine',
    'tropical_apricot': 'tropical_apricot',
    'wild_cherry': 'wild_cherry',
    'acorn': 'acorn',
    'almond': 'almond',
    'beechnut': 'beechnut',
    'black_walnut': 'black_walnut',
    'brazil_nut': 'brazil_nut',
    'breadnut': 'breadnut',
    'bunya_nut': 'bunya_nut',
    'butternut': 'butternut',
    'candlenut': 'candlenut',
    'cashew': 'cashew',
    'ginkgo_nut': 'ginkgo_nut',
    'hazelnut': 'hazelnut',
    'heartnut': 'heartnut',
    'hickory_nut': 'hickory_nut',
    'kola_nut': 'kola_nut',
    'kukui_nut': 'kukui_nut',
    'macadamia': 'macadamia',
    'mongongo': 'mongongo',
    'monkey_puzzle_nut': 'monkey_puzzle_nut',
    'nutmeg': 'nutmeg',
    'paradise_nut': 'paradise_nut',
    'pecan': 'pecan',
    'pine_nut': 'pine_nut',
    'pistachio': 'pistachio',
    'walnut': 'walnut'
    }

for(let woodType of Object.keys(FRUIT_WOOD_TYPES))
{
    generateRecipes(woodType)
}

function generateRecipes(woodType)
{
    let fruitFoodJSON = {
      "parent": "item/handheld",
      "textures": {
        "layer0": `tfcflorae:items/food/${woodType}`
      }
    }
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/food/${woodType}.json`, JSON.stringify(fruitFoodJSON, null, 2))
}