const fs = require('fs');

let STONE_TYPES = {
    'andesite': 'andesite',
    'arkose': 'arkose',
    'basalt': 'basalt',
    'blaimorite': 'blaimorite',
    'blueschist': 'blueschist',
    'boninite': 'boninite',
    'carbonatite': 'carbonatite',
    'cataclasite': 'cataclasite',
    'chalk': 'chalk',
    'chert': 'chert',
    'claystone': 'claystone',
    'conglomerate': 'conglomerate',
    'dacite': 'dacite',
    'diorite': 'diorite',
    'dolomite': 'dolomite',
    'foidolite': 'foidolite',
    'gabbro': 'gabbro',
    'gneiss': 'gneiss',
    'granite': 'granite',
    'greenschist': 'greenschist',
    'jaspillite': 'jaspillite',
    'limestone': 'limestone',
    'marble': 'marble',
    'mylonite': 'mylonite',
    'phyllite': 'phyllite',
    'quartzite': 'quartzite',
    'rhyolite': 'rhyolite',
    'rocksalt': 'rocksalt',
    'schist': 'schist',
    'shale': 'shale',
    'slate': 'slate',
    'travertine': 'travertine',
    'wackestone': 'wackestone',
	'breccia': 'breccia',
    'porphyry': 'porphyry',
    'peridotite': 'peridotite',
    'mudstone': 'mudstone',
    'sandstone': 'sandstone',
    'siltstone': 'siltstone',
    'catlinite': 'catlinite',
    'novaculite': 'novaculite',
    'soapstone': 'soapstone',
    'komatiite': 'komatiite'
}


for(let stoneType of Object.keys(STONE_TYPES))
{
    generateRecipes(stoneType)
}

function generateRecipes(stoneType)
{
        let cracked_bricksJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfc_decoration:blocks/stonetypes/cracked_bricks/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let mossy_bricksJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfc_decoration:blocks/stonetypes/mossy_bricks/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let mossy_cobbleJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfc_decoration:blocks/stonetypes/mossy_cobble/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let mud_bricksJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_all",
            "textures": {
              "all": `tfc_decoration:blocks/stonetypes/mud_bricks/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
        let sandstoneJSON = {
          "__comment": "Generated by generateResources.py function: blockstate",
          "forge_marker": 1,
          "defaults": {
            "model": "cube_bottom_top",
            "textures": {
              "side": `tfc_decoration:blocks/stonetypes/sandstone/side/${stoneType}`,
              "bottom": `tfc_decoration:blocks/stonetypes/sandstone/bottom/${stoneType}`,
              "top": `tfc_decoration:blocks/stonetypes/sandstone/top/${stoneType}`
            }
          },
          "variants": {
            "normal": [
              {}
            ]
          }
        }
    
    // Blocks
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/blockstates/cracked_bricks/${stoneType}.json`, JSON.stringify(cracked_bricksJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/blockstates/mossy_bricks/${stoneType}.json`, JSON.stringify(mossy_bricksJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/blockstates/mossy_cobble/${stoneType}.json`, JSON.stringify(mossy_cobbleJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/blockstates/mud_bricks/${stoneType}.json`, JSON.stringify(mud_bricksJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/blockstates/sandstone/${stoneType}.json`, JSON.stringify(sandstoneJSON, null, 2))

    let mud_ball_itemJSON = {
      "__comment": "Generated by generateResources.py function: model",
      "parent": "item/generated",
      "textures": {
        "layer0": `tfc_decoration:items/stonetypes/mud_ball/${stoneType}`
      }
    }
    let mud_brick_itemJSON = {
      "__comment": "Generated by generateResources.py function: model",
      "parent": "item/generated",
      "textures": {
        "layer0": `tfc_decoration:items/stonetypes/mud_brick/${stoneType}`
      }
    }
    let mud_bricks_itemJSON = {
      "__comment": "Generated by generateResources.py function: model",
      "parent": "item/generated",
      "textures": {
        "layer0": `tfc_decoration:items/stonetypes/mud_bricks/${stoneType}`
      }
    }

    // Items
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/models/item/mud_ball/${stoneType}.json`, JSON.stringify(mud_ball_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/models/item/mud_brick/${stoneType}.json`, JSON.stringify(mud_brick_itemJSON, null, 2))
    fs.writeFileSync(`./src/main/resources/assets/tfc_decoration/models/item/mud_bricks/${stoneType}.json`, JSON.stringify(mud_bricks_itemJSON, null, 2))
	
    let small_boulderJSON = {
		"populate":{
			`small_boulder_${stoneType}`:{
				"distribution":"surface",
				"generator":{
					"type":"boulder",
					"block":[
						{
							"name":`tfc_decoration:mossy_cobble/${stoneType}`,
							"weight":20
						},
						{
							"name":`tfcflorae:mossy_raw/${stoneType}`,
							"weight":20
						},
						{
							"name":`tfc:cobble/${stoneType}`,
							"weight":25
						},
						{
							"name":`tfc:raw/${stoneType}`,
							"weight":35
						}
					],
					"material":[
						`tfc:grass/${stoneType}`,
						`tfc:dry_grass/${stoneType}`,
						`tfc:dirt/${stoneType}`,
						`tfc:gravel/${stoneType}`,
						`tfcflorae:podzol/${stoneType}`
					],
					"diameter":1,
					"size-variance":1,
					"count":1,
					"count-variance":2
				},
				"chunk-chance":20,
				"cluster-count":10,
				"min-height":50,
				"max-height":170,
				"material":[
					"minecraft:air",
					`tfc:grass/${stoneType}`,
					`tfc:dry_grass/${stoneType}`,
					`tfc:dirt/${stoneType}`,
					`tfc:gravel/${stoneType}`,
					`tfcflorae:podzol/${stoneType}`
				],
				"follow-terrain":true,
				"retrogen":false,
				"biome":{
					"restriction":"whitelist",
					"value":[
						{
							"type":"dictionary",
							"entry":"FROZEN"
						},
						{
							"type":"dictionary",
							"entry":"SNOWY"
						},
						{
							"type":"dictionary",
							"entry":"SANDY"
						},
						{
							"type":"dictionary",
							"entry":"FOREST"
						},
						{
							"type":"dictionary",
							"entry":"MOUNTAIN"
						},
						{
							"type":"dictionary",
							"entry":"CONIFEROUS"
						},
						{
							"type":"dictionary",
							"entry":"PLAINS"
						},
						{
							"type":"dictionary",
							"entry":"SWAMP"
						},
						{
							"type":"dictionary",
							"entry":"LUSH"
						},
						{
							"type":"dictionary",
							"entry":"HILLS"
						}
					]
				},
				"dimension":{
					"restriction":"blacklist",
					"value":[
						-1,
						1
					]
				}
			}
		}
	}
    let medium_boulderJSON = {
		"populate": {	
			`medium_boulder_${stoneType}`: {
				"distribution": "surface",
				"generator": {
					"type": "boulder",
					"block": [
						{
							"name": `tfc_decoration:mossy_cobble/${stoneType}`
							"weight": 20
						},
						{
							"name": `tfcflorae:mossy_raw/${stoneType}`,
							"weight": 20
						},
						{
							"name": `tfc:cobble/${stoneType}`,
							"weight": 25
						},
						{
							"name": `tfc:raw/${stoneType}`,
							"weight": 35
						}
					],
					"material": [
						`tfc:grass/${stoneType}`,
						`tfc:dry_grass/${stoneType}`,
						`tfc:dirt/${stoneType}`,
						`tfc:gravel/${stoneType}`,
						`tfcflorae:podzol/${stoneType}`
					],
					"diameter": 2,
					"size-variance": 1,
					"count": 1,
					"count-variance": 2
				},
				"chunk-chance": 30,
				"cluster-count": 10,
				"min-height": 50,
				"max-height": 170,
				"material": [
					"minecraft:air",
					`tfc:grass/${stoneType}`,
					`tfc:dry_grass/${stoneType}`,
					`tfc:dirt/${stoneType}`,
					`tfc:gravel/${stoneType}`,
					`tfcflorae:podzol/${stoneType}`
				],
				"follow-terrain": true,
				"retrogen": false,
				"biome": {
					"restriction": "whitelist",
					"value": [
						{
							"type": "dictionary",
							"entry": "FROZEN"
						}, 
						{
							"type": "dictionary",
							"entry": "SNOWY"
						},
						{
							"type": "dictionary",
							"entry": "SANDY"
						},
						{
							"type": "dictionary",
							"entry": "FOREST"
						}, 
						{
							"type": "dictionary",
							"entry": "MOUNTAIN"
						}, 
						{
							"type": "dictionary",
							"entry": "CONIFEROUS"
						}, 
						{
							"type": "dictionary",
							"entry": "PLAINS"
						}, 
						{
							"type": "dictionary",
							"entry": "SWAMP"
						}, 
						{
							"type": "dictionary",
							"entry": "LUSH"
						}, 
						{
							"type": "dictionary",
							"entry": "HILLS"
						}
					]
				},
				"dimension": {
					"restriction": "blacklist",
					"value": [
						-1,
						1
					]
				}
			}
		}
	}
    let large_boulderJSON = {
		"populate": {	
			`large_boulder_${stoneType}`: {
				"distribution": "surface",
				"generator": {
					"type": "boulder",
					"block": [
						{
							"name": `tfc_decoration:mossy_cobble/${stoneType}`
							"weight": 20
						},
						{
							"name": `tfcflorae:mossy_raw/${stoneType}`,
							"weight": 20
						},
						{
							"name": `tfc:cobble/${stoneType}`,
							"weight": 25
						},
						{
							"name": `tfc:raw/${stoneType}`,
							"weight": 35
						}
					],
					"material": [
						`tfc:grass/${stoneType}`,
						`tfc:dry_grass/${stoneType}`,
						`tfc:dirt/${stoneType}`,
						`tfc:gravel/${stoneType}`,
						`tfcflorae:podzol/${stoneType}`
					],
					"diameter": 2,
					"size-variance": 1,
					"count": 1,
					"count-variance": 2
				},
				"chunk-chance": 40,
				"cluster-count": 10,
				"min-height": 50,
				"max-height": 170,
				"material": [
					"minecraft:air",
					`tfc:grass/${stoneType}`,
					`tfc:dry_grass/${stoneType}`,
					`tfc:dirt/${stoneType}`,
					`tfc:gravel/${stoneType}`,
					`tfcflorae:podzol/${stoneType}`
				],
				"follow-terrain": true,
				"retrogen": false,
				"biome": {
					"restriction": "whitelist",
					"value": [
						{
							"type": "dictionary",
							"entry": "FROZEN"
						}, 
						{
							"type": "dictionary",
							"entry": "SNOWY"
						},
						{
							"type": "dictionary",
							"entry": "SANDY"
						},
						{
							"type": "dictionary",
							"entry": "FOREST"
						}, 
						{
							"type": "dictionary",
							"entry": "MOUNTAIN"
						}, 
						{
							"type": "dictionary",
							"entry": "CONIFEROUS"
						}, 
						{
							"type": "dictionary",
							"entry": "PLAINS"
						}, 
						{
							"type": "dictionary",
							"entry": "SWAMP"
						}, 
						{
							"type": "dictionary",
							"entry": "LUSH"
						}, 
						{
							"type": "dictionary",
							"entry": "HILLS"
						}
					]
				},
				"dimension": {
					"restriction": "blacklist",
					"value": [
						-1,
						1
					]
				}
			}
		}
	}
	
    // Boulders
    fs.writeFileSync(`./cofh/world/boulder/small/${stoneType}.json`, JSON.stringify(small_boulderJSON, null, 2))
    fs.writeFileSync(`./cofh/world/boulder/medium/${stoneType}.json`, JSON.stringify(medium_boulderJSON, null, 2))
    fs.writeFileSync(`./cofh/world/boulder/large/${stoneType}.json`, JSON.stringify(large_boulderJSON, null, 2))
}
