const fs = require('fs');

let DRIED_FOOD_TYPES = {
    'abiu': 'abiu',
    'amla': 'amla',
    'apricot': 'apricot',
    'avocado': 'avocado',
    'bael': 'bael',
    'bay_laurel': 'bay_laurel',
    'ber': 'ber',
    'bergamot': 'bergamot',
    'black_cherry': 'black_cherry',
    'black_pepper': 'black_pepper',
    'blackcurrant': 'blackcurrant',
    'blackthorn': 'blackthorn',
    'buddha_hand': 'buddha_hand',
    'cacao': 'cacao',
    'cherry_plum': 'cherry_plum',
    'citron': 'citron',
    'coconut': 'coconut',
    'coffea': 'coffea',
    'crabapple': 'crabapple',
    'damson_plum': 'damson_plum',
    'date': 'date',
    'elder': 'elder',
    'elderberry': 'elderberry',
    'fig': 'fig',
    'finger_lime': 'finger_lime',
    'grapefruit': 'grapefruit',
    'guava': 'guava',
    'ice_cream_bean': 'ice_cream_bean',
    'jackfruit': 'jackfruit',
    'jujube': 'jujube',
    'juniper': 'juniper',
    'kaki': 'kaki',
    'key_lime': 'key_lime',
    'kluwak': 'kluwak',
    'kumquat': 'kumquat',
    'lime': 'lime',
    'longan': 'longan',
    'loquat': 'loquat',
    'lychee': 'lychee',
    'mamey_sapote': 'mamey_sapote',
    'manderin': 'manderin',
    'mango': 'mango',
    'mangosteen': 'mangosteen',
    'nectarine': 'nectarine',
    'ohia_ai': 'ohia_ai',
    'osage_orange': 'osage_orange',
    'papaya': 'papaya',
    'passion_fruit': 'passion_fruit',
    'pear': 'pear',
    'persimmon': 'persimmon',
    'persian_lime': 'persian_lime',
    'peruvian_pepper': 'peruvian_pepper',
    'plantain': 'plantain',
    'plum': 'plum',
    'pomegranate': 'pomegranate',
    'pomelo': 'pomelo',
    'quince': 'quince',
    'rainier_cherry': 'rainier_cherry',
    'red_banana': 'red_banana',
    'red_currant': 'red_currant',
    'sand_pear': 'sand_pear',
    'sapodilla': 'sapodilla',
    'satsuma': 'satsuma',
    'sour_cherry': 'sour_cherry',
    'soursop': 'soursop',
    'star_anise': 'star_anise',
    'starfruit': 'starfruit',
    'tamarillo': 'tamarillo',
    'tangerine': 'tangerine',
    'tropical_apricot': 'tropical_apricot',
    'wild_cherry': 'wild_cherry',
    'banana': 'banana',
    'cherry': 'cherry',
    'olive': 'olive',
    'red_apple': 'red_apple',
    'green_apple': 'green_apple',
    'lemon': 'lemon',
    'orange': 'orange',
    'peach': 'peach',
    'plum': 'plum',
    'black_pepper': 'black_pepper',
    'black_tea': 'black_tea',
    'green_tea': 'green_tea',
    'white_tea': 'white_tea',
    'cannabis_bud': 'cannabis_bud',
    'cannabis_leaf': 'cannabis_leaf',
    'coca_leaf': 'coca_leaf',
    'opium_poppy_bulb': 'opium_poppy_bulb',
    'peyote': 'peyote',
    'tobacco_leaf': 'tobacco_leaf',
    'cocoa_beans': 'cocoa_beans',
    'coffea_cherries': 'coffea_cherries',
    'blackberry': 'blackberry',
    'blueberry': 'blueberry',
    'bunch_berry': 'bunch_berry',
    'cloud_berry': 'cloud_berry',
    'cranberry': 'cranberry',
    'elderberry': 'elderberry',
    'gooseberry': 'gooseberry',
    'raspberry': 'raspberry',
    'snow_berry': 'snow_berry',
    'strawberry': 'strawberry',
    'wintergreen_berry': 'wintergreen_berry'
    }

for(let driedFoodType of Object.keys(DRIED_FOOD_TYPES))
{
    generateRecipes(driedFoodType)
}

function generateRecipes(driedFoodType)
{
    let driedFoodJSON = {
      "parent": "item/handheld",
      "textures": {
        "layer0": `tfcflorae:items/food/dried/${driedFoodType}`
      }
    }
    fs.writeFileSync(`./src/main/resources/assets/tfcflorae/models/item/food/dried/${driedFoodType}.json`, JSON.stringify(driedFoodJSON, null, 2))
}